return PlaceObj('ModDef', {
	'title', "JAZZ Units",
	'description', "Мод для работы основного JAZZ модаВ",
	'image', "Mod/Dv3mFVN/Images/JAZZLOGO.jpg",
	'last_changes', "Обновленны архетипы",
	'id', "Dv3mFVN",
	'author', "Doctor_Leevsy",
	'version_minor', 1,
	'version', 1613,
	'lua_revision', 233360,
	'saved_with_revision', 366685,
	'code', {
		"UnitData/LegionRocketeer_Stronger_Elite.lua",
		"UnitData/LegionSharpShooter_Stronger_Elite.lua",
		"UnitData/LegionRaider_Stronger_Elite.lua",
		"UnitData/LegionRaider_Demolution_Stronger_Elite.lua",
		"UnitData/LegionRaidLeader_Stronger_Elite.lua",
		"UnitData/LegionManiac_Stronger_Elite.lua",
		"UnitData/LegionMedic_Stronger_Elite.lua",
		"UnitData/LegionGunner_Stronger_Elite.lua",
		"UnitData/LegionHyenaHandler_Stronger_Elite.lua",
		"UnitData/LegionGrenadier_Stronger_Elite.lua",
		"UnitData/LegionGoon_Stronger_Elite.lua",
		"UnitData/LegionButcher_Stronger_Elite.lua",
		"UnitData/LegionScout_Stronger_Elite.lua",
		"UnitData/LegionSniper_Stronger_Elite.lua",
		"UnitData/LegionSergant_Stronger_Elite.lua",
		"UnitData/LegionRanger_Stronger_Elite.lua",
		"UnitData/LegionMortarman_Stronger_Elite.lua",
		"UnitData/LegionRocketeer_Stronger.lua",
		"UnitData/LegionRaider_Stronger.lua",
		"UnitData/LegionRaider_Demolution_Stronger.lua",
		"UnitData/LegionRaidLeader_Stronger.lua",
		"UnitData/LegionMortarman_Stronger.lua",
		"UnitData/LegionMedic_Stronger.lua",
		"UnitData/LegionManiac_Stronger.lua",
		"UnitData/LegionHyenaHandler_Stronger.lua",
		"UnitData/LegionHyena_Stronger.lua",
		"UnitData/LegionGunner_Stronger.lua",
		"UnitData/LegionGrenadier_Stronger.lua",
		"UnitData/LegionMolotov_Stronger.lua",
		"UnitData/LegionGoon_Stronger.lua",
		"UnitData/LegionButcher_Stronger.lua",
		"UnitData/LegionScout_Stronger.lua",
		"UnitData/LegionSharpShooter_Stronger.lua",
		"UnitData/LegionSniper_Stronger.lua",
		"UnitData/LegionSergant_Stronger.lua",
		"UnitData/LegionRanger_Stronger.lua",
		"UnitData/LegionRaider.lua",
		"UnitData/LegionRaider_Demolution.lua",
		"UnitData/LegionRaidLeader.lua",
		"UnitData/LegionMedic.lua",
		"UnitData/LegionManiac.lua",
		"UnitData/LegionGunner.lua",
		"UnitData/LegionGrenadier.lua",
		"UnitData/LegionMolotov.lua",
		"UnitData/LegionGoon.lua",
		"UnitData/LegionButcher.lua",
		"UnitData/LegionScout.lua",
		"UnitData/LegionSniper.lua",
		"UnitData/LegionSharpShooter.lua",
		"UnitData/LegionRocketeer.lua",
		"UnitData/ArmyCommando_Sergant.lua",
		"UnitData/ArmyCommando_Demolution.lua",
		"UnitData/ArmyCommando_Sniper.lua",
		"UnitData/ArmyCommando_Scout.lua",
		"UnitData/ArmyStormer.lua",
		"UnitData/ArmySoldier.lua",
		"UnitData/ArmySniper_Elite.lua",
		"UnitData/ArmySniper.lua",
		"UnitData/ArmyScout.lua",
		"UnitData/ArmyRPG.lua",
		"UnitData/ArmyMortar.lua",
		"UnitData/ArmyMedic.lua",
		"UnitData/ArmyMedic_Elite.lua",
		"UnitData/ArmyHeavy.lua",
		"UnitData/ArmyDemo_Elite.lua",
		"UnitData/ArmyDemo.lua",
		"UnitData/ArmyCommander_Elite.lua",
		"UnitData/ArmyCommanderFemale.lua",
		"UnitData/ArmyCommander.lua",
		"UnitData/ArmyLeitenant.lua",
		"UnitData/ArmySergant.lua",
		"UnitData/CorazonGuard.lua",
		"UnitData/AdonisStormer_Elite.lua",
		"UnitData/AdonisStormer.lua",
		"UnitData/AdonisAssault_Elite.lua",
		"UnitData/AdonisAssault.lua",
		"UnitData/AdonisSquadLeader_Elite.lua",
		"UnitData/AdonisSquadLeader.lua",
		"UnitData/AdonisSquadLeader_Heavy.lua",
		"UnitData/AdonisSquadLeader_Corporal.lua",
		"UnitData/AdonisSquadLeader_Sergant.lua",
		"UnitData/AdonisSniper_Elite.lua",
		"UnitData/AdonisSniper.lua",
		"UnitData/AdonisMortar.lua",
		"UnitData/AdonisMedic.lua",
		"UnitData/AdonisHeavy.lua",
		"UnitData/AdonisDedicatedGunner_Elite.lua",
		"UnitData/AdonisFlanker_Elite.lua",
		"UnitData/AdonisFlanker.lua",
		"UnitData/AdonisDemolitions_Elite.lua",
		"UnitData/AdonisDemolitions.lua",
		"UnitData/AdonisSoldier.lua",
		"UnitData/AdonisSoldier_Elite.lua",
		"UnitData/Chimurenga.lua",
		"UnitData/RebelSergant_Immortal.lua",
		"UnitData/RebelSergant.lua",
		"UnitData/RebelFlanker.lua",
		"UnitData/RebelGrenadier.lua",
		"UnitData/RebelGunner.lua",
		"UnitData/RebelSentry.lua",
		"UnitData/RebelSniper.lua",
		"UnitData/RebelSniper_female.lua",
		"UnitData/RebelSoldier.lua",
		"UnitData/RebelRPG.lua",
		"UnitData/RebelRPG_Immortal.lua",
		"UnitData/RebelHeavy_Mortar.lua",
		"UnitData/RebelHeavy_Mortar_Immortal.lua",
		"UnitData/MilitiaVeteran.lua",
		"UnitData/MilitiaRookie.lua",
		"UnitData/MilitiaElite.lua",
		"UnitData/PierreGuard_Ordnance.lua",
		"UnitData/ErnyVillage_Boss.lua",
		"UnitData/PierreGuard.lua",
		"UnitData/LegionRocketeer_SlowReloader.lua",
		"UnitData/LegionRaider_PresidentGuard.lua",
		"UnitData/LegionRaider_Ernie_Elite.lua",
		"UnitData/LegionBrawler_SavannaCamp.lua",
		"UnitData/LegionRaider_WeakFlagHill.lua",
		"UnitData/Jazz_lynx.lua",
		"UnitData/Jazz_Buzz.lua",
		"UnitData/Jazz_Spider.lua",
		"UnitData/JAZZ_Ivanov.lua",
		"UnitData/JAZZ_Merc_Spouke.lua",
		"UnitData/Smiley.lua",
		"UnitData/PierreMerc.lua",
		"UnitData/Omryn.lua",
		"UnitData/Livewire.lua",
		"UnitData/Kalyna.lua",
		"UnitData/Flay.lua",
		"UnitData/Fauda.lua",
		"UnitData/Wolf.lua",
		"UnitData/Vicki.lua",
		"UnitData/Thor.lua",
		"UnitData/Tex.lua",
		"UnitData/Steroid.lua",
		"UnitData/Spike.lua",
		"UnitData/Sidney.lua",
		"UnitData/Shadow.lua",
		"UnitData/Scully.lua",
		"UnitData/Scope.lua",
		"UnitData/Red.lua",
		"UnitData/Reaper.lua",
		"UnitData/Raven.lua",
		"UnitData/Raider.lua",
		"UnitData/Nails.lua",
		"UnitData/Mouse.lua",
		"UnitData/Meltdown.lua",
		"UnitData/Magic.lua",
		"UnitData/MD.lua",
		"UnitData/Len.lua",
		"UnitData/Larry.lua",
		"UnitData/Larry_Clean.lua",
		"UnitData/Ivan.lua",
		"UnitData/Igor.lua",
		"UnitData/Ice.lua",
		"UnitData/Hitman.lua",
		"UnitData/Gus.lua",
		"UnitData/Grunty.lua",
		"UnitData/Grizzly.lua",
		"UnitData/Fox.lua",
		"UnitData/Fidel.lua",
		"UnitData/DrQ.lua",
		"UnitData/Buns.lua",
		"UnitData/Blood.lua",
		"UnitData/Barry.lua",
		"Code/ExperienceSys.lua",
		"Code/ExperienceTable.lua",
		"Code/StatGainRework.lua",
		"CharacterEffect/TheGrim.lua",
		"CharacterEffect/VengefulTemperament.lua",
	},
	'default_options', {},
	'has_data', true,
	'saved', 1752411534,
	'code_hash', 5328858094426055850,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRocketeer_Stronger_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionSharpShooter_Stronger_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRaider_Stronger_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRaider_Demolution_Stronger_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRaidLeader_Stronger_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionManiac_Stronger_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionMedic_Stronger_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionGunner_Stronger_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionHyenaHandler_Stronger_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionGrenadier_Stronger_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionGoon_Stronger_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionButcher_Stronger_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionScout_Stronger_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionSniper_Stronger_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionSergant_Stronger_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRanger_Stronger_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionMortarman_Stronger_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRocketeer_Stronger",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRaider_Stronger",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRaider_Demolution_Stronger",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRaidLeader_Stronger",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionMortarman_Stronger",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionMedic_Stronger",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionManiac_Stronger",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionHyenaHandler_Stronger",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionHyena_Stronger",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionGunner_Stronger",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionGrenadier_Stronger",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionMolotov_Stronger",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionGoon_Stronger",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionButcher_Stronger",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionScout_Stronger",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionSharpShooter_Stronger",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionSniper_Stronger",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionSergant_Stronger",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRanger_Stronger",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRaider",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRaider_Demolution",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRaidLeader",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionMedic",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionManiac",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionGunner",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionGrenadier",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionMolotov",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionGoon",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionButcher",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionScout",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionSniper",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionSharpShooter",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRocketeer",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmyCommando_Sergant",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmyCommando_Demolution",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmyCommando_Sniper",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmyCommando_Scout",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmyStormer",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmySoldier",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmySniper_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmySniper",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmyScout",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmyRPG",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmyMortar",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmyMedic",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmyMedic_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmyHeavy",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmyDemo_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmyDemo",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmyCommander_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmyCommanderFemale",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmyCommander",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmyLeitenant",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ArmySergant",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "CorazonGuard",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisStormer_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisStormer",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisAssault_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisAssault",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisSquadLeader_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisSquadLeader",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisSquadLeader_Heavy",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisSquadLeader_Corporal",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisSquadLeader_Sergant",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisSniper_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisSniper",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisMortar",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisMedic",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisHeavy",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisDedicatedGunner_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisFlanker_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisFlanker",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisDemolitions_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisDemolitions",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisSoldier",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisSoldier_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Chimurenga",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "RebelSergant_Immortal",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "RebelSergant",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "RebelFlanker",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "RebelGrenadier",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "RebelGunner",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "RebelSentry",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "RebelSniper",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "RebelSniper_female",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "RebelSoldier",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "RebelRPG",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "RebelRPG_Immortal",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "RebelHeavy_Mortar",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "RebelHeavy_Mortar_Immortal",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemyRole",
			'Id', "Militia",
			'ClassDisplayName', "EnemyRole",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "MilitiaVeteran",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "MilitiaRookie",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "MilitiaElite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionAttackers_Balanced_Easy_Assault",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "NNightSquadSappers",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "NNightSquad",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionHeavyTroops",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionAttackers_Marksmen_Easy",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionDefenders_Mobile_Easy",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionAttackers_JazzBalanced_Easy_Assault",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionExtraDefenders_Marksmen_Hard",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionHeavyTroops_Gunners",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionExtraSquadFireArms",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionExtraSquadFireArms_T2",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionExtraSquadFireArms_T3",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionExtraSquadMelee",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionExtraSquadMeleeV2",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionExtraSquadMelee_T2",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionExtraSquadMelee_T3",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionExtraSquadAnimal",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "FortressDefenders",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionFortressDefenders",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionDefenders_Shooters_Easy",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionDefenders_Shooters_Easy_Ernie",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionErnieVillage",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionOutlook_Easy",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionRustIni",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionJAZZSquadT1",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionJAZZSquadT1_Ernie",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionJAZZSquadT2",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "LegionJAZZSquadT3",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "OutlookPatrool",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "Beach_Patrol",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "Legion_Patrol_1",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "Legion_Patrol_2",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "Legion_Patrol_3",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "3rd_Patrol",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "ArmySpecOps",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "ArmySpecOps_alt",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "ArmyIfantry_Support",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "ArmyIfantry_Support_MG",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "ArmyIfantry_Support_Sniper",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "ArmyIfantry_Support_Shooter",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "ArmyAttackers_Balanced_Hard",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "ArmyAttackers_Balanced_Alt",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "Adonis_Troops_Assault_Light",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "Adonis_Troops_Assault_Heavy",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "Adonis_Troops_Defenders_Light",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "Adonis_Troops_Defenders_Heavy",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "Adonis_Support_MachineGuns",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "Adonis_Support_SniperSquad",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "Adonis_Support_HeavyInfantry",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "Adonis_Heavy_Troops",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "Adonis_Heavy_Troops_Alt",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "Adonis_SpecOps_Light",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "Adonis_SpecOps_Light_Alt",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "Adonis_SpecOps_Heavy",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "EnemySquads",
			'Id', "Adonis_SpecOps_Heavy_Alt",
			'ClassDisplayName', "Enemy Squads",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Beast_Hyena",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "TurretBoss",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "TheMajor",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "__Scout_LastLocation",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Scout_LastLocation",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "PierreGuard",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "PinnedDown",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Panicked",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "GuardArea",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "EmplacementGunner",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Deserter",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Berserk",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Artillery",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Turret",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Medic",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Medic_Low",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Grenadier",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Soldier",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Skirmisher",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Soldier_Sniper",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "HeavyGunner",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Brute",
			'ClassDisplayName', "AIArchetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionButcher",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionButcher_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionButcher_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionButcher_alt_3",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGoon",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGoon_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGoon_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGoon_alt_3",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGrenadir",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGrenadir_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGrenadir_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGunner",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGunner_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRaider",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRaider_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRaider_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRaidLeader",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRaidLeader_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRaidLeader_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionMedic",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionMedic_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionManiac",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionManiac_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionManiac_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionScout",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionScout_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionScout_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionSniper",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionSniper_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionSniper_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionSharpShooter",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionSharpShooter_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionSharpShooter_alt_1",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionButcher_Stronger",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionButcher_Stronger_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionButcher_Stronger_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGoon_Stronger",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGoon_Stronger_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGoon_Stronger_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGrenadir_Stronger",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGrenadir_Stronger_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGrenadir_Stronger_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGunner_Stronger",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGunner_Stronger_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGunner_Stronger_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionHyenaHandler_Stronger",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionHyenaHandler_Stronger_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionHyenaHandler_Stronger_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionManiac_Stronger",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionManiac_Stronger_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionManiac_Stronger_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionMedic_Stronger",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionMedic_Stronger_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionMedic_Stronger_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionMortalman_Stronger",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionMortalman_Stronger_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionMortalman_Stronger_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRanger_Stronger",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRanger_Stronger_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRanger_Stronger_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRaider_Stronger",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRaider_Stronger_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRaider_Stronger_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRaider_Stronger_alt_3",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRaidLeader_Stronger",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRaidLeader_Stronger_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRaidLeader_Stronger_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRoceteer_Stronger",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRoceteer_Stronger_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionSharpShooter_Stronger",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionSharpShooter_Stronger_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionSharpShooter_Stronger_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionScout_Stronger",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionScout_Stronger_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionScout_Stronger_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionSniper_Stronger",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionSniper_Stronger_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionSniper_Stronger_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionSergant_Stronger",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionSergant_Stronger_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionSergant_Stronger_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionButcher_Stronger_Elite",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionButcher_Stronger_Elite_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionButcher_Stronger_Elite_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGoon_Stronger_Elite",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGoon_Stronger_Elite_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGoon_Stronger_Elite_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGrenadir_Stronger_Elite",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGrenadir_Stronger_Elite_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRoceteer_Stronger_Elite",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRoceteer_Stronger_Elite_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRanger_Stronger_Elite",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRanger_Stronger_Elite_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRaider_Stronger_Elite",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRaider_Stronger_Elite_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRaider_Stronger_Elite_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRaidLeader_Stronger_Elite",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionRaidLeader_Stronger_Elite_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionHyenaHandler_Stronger_Elite",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionHyenaHandler_Stronger_Elite_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionManiac_Stronger_Elite",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionManiac_Stronger_Elite_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGunner_Stronger_Elite",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionGunner_Stronger_Elite_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionMedic_Stronger_Elite",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionMedic_Stronger_Elite_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionMortalman_Stronger_Elite",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionMortalman_Stronger_Elite_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionScout_Stronger_Elite",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionScout_Stronger_Elite_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionScout_Stronger_Elite_alt_2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionSniper_Stronger_Elite",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionSniper_Stronger_Elite_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionSergant_Stronger_Elite",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "LegionSergant_Stronger_Elite_alt",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "PierreGuard_Ordnance",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "ErnyVillage_Boss",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "PierreGuard",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRocketeer_SlowReloader",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRaider_PresidentGuard",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRaider_Ernie_Elite",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionBrawler_SavannaCamp",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRaider_WeakFlagHill",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Jazz_lynx",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Jazz_Buzz",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Jazz_Spider",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "JAZZ_Ivanov",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "VoiceResponse",
			'Id', "Jazz_Ivanov",
			'ClassDisplayName', "Unit voice responses",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Ivanov",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "JAZZ_Spouke_Ice",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "VoiceResponse",
			'Id', "JAZZ_Merc_Spouke",
			'ClassDisplayName', "Unit voice responses",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "JAZZ_Merc_Spouke",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Smiley",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "PierreMerc",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Omryn",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Livewire",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Kalyna",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Flay",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Fauda",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Wolf",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Vicki",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Thor",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Tex",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Steroid",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Spike",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Sidney",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Shadow",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Scully",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Scope",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Red",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Reaper",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Raven",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Raider",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Nails",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Mouse",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Meltdown",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Magic",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "MD",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Len",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Larry",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Larry_Clean",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Ivan",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Igor",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Ice",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Hitman",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Gus",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Grunty",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Grizzly",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Fox",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Fidel",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "DrQ",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Buns",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Blood",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Barry",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "JAZZ_Spouke",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Spider",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Wolf_DustStorm",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Steroid_DustStorm",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Sidney_DustStorm",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Reaper_Snake",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Scope_DustStorm",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Red_DustStorm",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Reaper_DustStorm",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Reaper_Jungle",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Raven_DustStorm",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Raider_DustStorm",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Omryn_DustStorm",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Nails_DustStorm",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Magic_DustStorm",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "MD_Savana",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "MD_Jungle",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Len_Hot",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Larry_Savana_DustStorm",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Kalyna_Hot",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Ivan_Hot",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Lynx",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Buzz",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Igor_DustStorm",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Ice_DustStorm",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Hitman_Savana_DustStorm",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Hitman_Jungle",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Gus_Savana",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Grunty_Savana",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Grunty_Jungle",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Grizzly_Savana_DustStorm",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Fox_Savana_Hot",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Fox_Jungle",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "DrQ_Savana",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "DrQ_Jungle",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Scully_Forest",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Scully_Savana",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Buns_Savana",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Blood_Savana",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Barry_Savana",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "StatGainingPrerequisite",
			'Id', "ResourceDiscovery",
			'Prop', "failChance",
			'ClassDisplayName', "StatGainingPrerequisites",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "StatGainingPrerequisite",
			'Id', "ExplosiveMultiHit",
			'Prop', "failChance",
			'ClassDisplayName', "StatGainingPrerequisites",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "StatGainingPrerequisite",
			'Id', "TrapDiscovery",
			'Prop', "oncePerMapVisit",
			'ClassDisplayName', "StatGainingPrerequisites",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "StatGainingPrerequisite",
			'Id', "TrapDiscovery",
			'Prop', "failChance",
			'ClassDisplayName', "StatGainingPrerequisites",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "StatGainingPrerequisite",
			'Id', "ResourceDiscovery",
			'Prop', "oncePerMapVisit",
			'ClassDisplayName', "StatGainingPrerequisites",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "StatGainingPrerequisite",
			'Id', "TrapDisarmMechanical",
			'Prop', "oncePerMapVisit",
			'ClassDisplayName', "StatGainingPrerequisites",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "StatGainingPrerequisite",
			'Id', "TrapDisarmExplosives",
			'Prop', "oncePerMapVisit",
			'ClassDisplayName', "StatGainingPrerequisites",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "VengefulTemperament1",
			'ClassDisplayName', "Combat Actions",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "TheGrim",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "VengefulTemperament",
			'ClassDisplayName', "Character effect",
		}),
	},
	'steam_id', "3323312979",
})