UndefineClass('ErnyVillage_Boss')
DefineClass.ErnyVillage_Boss = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",


	comment = "--Босс в деревне Эрни",
	object_class = "UnitData",
	Health = 100,
	Agility = 98,
	Dexterity = 98,
	Strength = 100,
	Wisdom = 80,
	Will = 100,
	Leadership = 100,
	Marksmanship = 100,
	Mechanical = 100,
	Explosives = 90,
	Medical = 90,
	Portrait = "UI/EnemiesPortraits/LegionOfficer",
	BigPortrait = "UI/Enemies/LegionRaider",
	Name = T(890000000000343, --[[ModItemUnitDataCompositeDef ErnyVillage_Boss Name]] "Босс"),
	Randomization = true,
	elite = true,
	eliteCategory = "Legion",
	Affiliation = "Legion",
	StartingLevel = 8,
	villain = true,
	neutral_retaliate = true,
	AIKeywords = {
		"Smoke",
		"Soldier",
		"Flank",
		"Marksman",
		"Control",
		"Leader",
	},
	archetype = "Legion_Frontliner",
	role = "Commander",
	AlwaysUseOpeningAttack = true,
	OpeningAttackType = "Overwatch",
	MaxAttacks = 10,
	PickCustomArchetype = function (self, proto_context)  end,
	CustomEquipGear = function (self, items)  end,
	MaxHitPoints = 80,
	StartingPerks = {
		"Spotter",
		"SidneyPerk",
		"TakeAim",
		"OnMyTarget",
		"Ironclad",
		"LightStep",
		"TrickShot",
		"LeadFromTheFront",
		"Shatterhand",
		"StressManagement",
		"Hotblood",
		"Instagib",
		"LightningReaction",
		"HitTheDeck",
		"CollateralDamage",
		"Hardened",
		"Spiritual",
		"BattleFocus",
		"RelentlessAdvance",
		"ShoulderToShoulder",
		"TrueGrit",
		"OverwatchExpert",
		"VengefulTemperament",
		"HeavyWeaponsTraining",
		"TagTeam",
		"BeefedUp",
		"Killzone",
		"CQCTraining",
		"Hobbler",
		"AutoWeapons",
		"WeGotThis",
	},
	AppearancesList = {
		PlaceObj('AppearanceWeight', {
			'Preset', "Legion_Shaman",
		}),
		PlaceObj('AppearanceWeight', {
			'Preset', "LegionRaidLeader_Stronger_Elite",
			'Weight', 3,
		}),
		PlaceObj('AppearanceWeight', {
			'Preset', "LegionRaidLeader_Stronger_Elite_alt",
			'Weight', 3,
		}),
	},
	Equipment = {
		"MercenaryCaptain_Inventory",
	},
	AdditionalGroups = {
		PlaceObj('AdditionalGroup', {
			'Weight', 50,
			'Exclusive', true,
			'Name', "LegionMale_1",
		}),
		PlaceObj('AdditionalGroup', {
			'Weight', 50,
			'Exclusive', true,
			'Name', "LegionMale_2",
		}),
	},
	pollyvoice = "Joey",
	gender = "Male",
	VoiceResponseId = "LegionRaider",
}

