UndefineClass('Jazz_Biggens')
DefineClass.Jazz_Biggens = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AIM",
	Health = 60,
	Agility = 55,
	Dexterity = 55,
	Strength = 55,
	Wisdom = 70,
	Will = 50,
	Leadership = 40,
	Marksmanship = 71,
	Mechanical = 50,
	Explosives = 92,
	Medical = 20,
	Portrait = "Mod/Dv3mFVN/MercPortraits/Biggens.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/Biggens_Big.png",
	IsMercenary = true,
	Name = T(890000000004699, "Полковник Фредерик Биггенс"),
	Nick = T(890000000004700, "Биггенс"),
	AllCapsNick = T(890000000004701, "БИГГЕНС"),
	Bio = T(890000000004702, "Ветеран из Urban Brawl. Статы 55–65, Marksmanship 71, Explosives 92. Оптимист, плохо переносит жару. Ставит заряды по старой школе — надёжно и аккуратно."),
	Nationality = "USA",
	Title = T(890000000004703, "Усталый дед"),
	Email = T(890000000004704, "Biggens@ub.mil"),
	snype_nick = T(890000000004705, "biggens"),
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000004706, --[[ModItemUnitDataCompositeDef Jazz_Biggens Text Offline ChatMessage voice:Jazz_Biggens]] "Биггенс отдыхает. Перезвоните.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000004707, --[[ModItemUnitDataCompositeDef Jazz_Biggens Text GreetingAndOffer ChatMessage voice:Jazz_Biggens]] "Полковник Биггенс слушает.") }) },
	ConversationRestart = { PlaceObj('ChatMessage', { 'Text', T(890000000004708, --[[ModItemUnitDataCompositeDef Jazz_Biggens Text ConversationRestart ChatMessage voice:Jazz_Biggens]] "Связь прервалась. Вернёмся к делу.") }) },
	IdleLine = { PlaceObj('ChatMessage', { 'Text', T(890000000004709, --[[ModItemUnitDataCompositeDef Jazz_Biggens Text IdleLine ChatMessage voice:Jazz_Biggens]] "Жарковато сегодня, но не жалуюсь.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000004710, --[[ModItemUnitDataCompositeDef Jazz_Biggens Text PartingWords ChatMessage voice:Jazz_Biggens]] "Ещё один заряд не помешает. Иду.") }) },
	RehireIntro = { PlaceObj('ChatMessage', { 'Text', T(890000000004711, --[[ModItemUnitDataCompositeDef Jazz_Biggens Text RehireIntro ChatMessage voice:Jazz_Biggens]] "Контракт заканчивается. Продлеваем?") }) },
	RehireOutro = { PlaceObj('ChatMessage', { 'Text', T(890000000004712, --[[ModItemUnitDataCompositeDef Jazz_Biggens Text RehireOutro ChatMessage voice:Jazz_Biggens]] "Остаюсь. Дело своё знаю.") }) },
	MedicalDeposit = "small",
	StartingSalary = 900,
	SalaryIncrease = 150,
	SalaryLv1 = 400,
	SalaryMaxLv = 2500,
	StartingLevel = 3,
	CustomEquipGear = function (self, items)
	self:TryEquip(items, "Handheld A", "Firearm")
	self:TryEquip(items, "Handheld B", "Firearm")
	end,
	MaxHitPoints = 60,
	StartingPerks = {
	"Jazz_Perk_Biggens",
	"Optimist",
	"NightOps",
	},
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "Biggens" }) },
	Equipment = { "Loot_JAZZ_Biggens" },
	Tier = "Regular",
	Specialization = "ExplosiveExpert",
	pollyvoice = "Matthew",
	gender = "Male",
	VoiceResponseId = "Jazz_Biggens",
	FallbackMissingVR = "Ice",
	DaysUntilOnline = 0,
}
