UndefineClass('JAZZ_AME_11')
DefineClass.JAZZ_AME_11 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 78,
	Agility = 58,
	Dexterity = 56,
	Strength = 42,
	Wisdom = 74,
	Will = 20,
	Leadership = 0,
	Marksmanship = 30,
	Mechanical = 0,
	Explosives = 0,
	Medical = 0,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_11.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_11_Big.png",
	IsMercenary = true,
	Name = T(890000000005200, "Aisha Hassan") --[[ModItemUnitDataCompositeDef JAZZ_AME_11 Name]],
	Nick = T(890000000005201, "Aisha") --[[ModItemUnitDataCompositeDef JAZZ_AME_11 Nick]],
	AllCapsNick = T(890000000005202, "AISHA") --[[ModItemUnitDataCompositeDef JAZZ_AME_11 AllCapsNick]],
	Bio = T(890000000005203, "The brass token from Aisha Hassan's old dock locker hangs on a cord, its stamped edge polished by sleepless fingers. Years of crates slamming down beside her boots ended when she finally left the Kenyan port. Sharp sounds still catch Aisha's breath, and embarrassment can turn fright into a cutting reply. She is slight and unseasoned, but knows how to keep moving through cramped spaces when everyone is tired.") --[[ModItemUnitDataCompositeDef JAZZ_AME_11 Bio]],
	Nationality = "Kenya",
	HireStatus = "NotMet",
	AMECategory = "Irregulars",
	AMERole = "Rifle",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005204, "You're through. I'm listening.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005205, "I'm looking for work. What do you have?") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005206, "All right. Speak soon.") }) },
	MedicalDeposit = "none",
	StartingSalary = 23,
	StartingLevel = 1,
	StartingPerks = {
	"Psycho",
	},
	Specialization = "AllRounder",
	MaxHitPoints = 78,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_11" }) },
	Equipment = { "Loot_JAZZ_AME_11" },
	gender = "Female",
	VoiceResponseId = "Jazz_AME_Female",
	FallbackMissingVR = "AnneLeMitrailleur",
	DaysUntilOnline = 0,
}
