UndefineClass('JAZZ_AME_44')
DefineClass.JAZZ_AME_44 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 80,
	Agility = 70,
	Dexterity = 68,
	Strength = 64,
	Wisdom = 52,
	Will = 54,
	Leadership = 16,
	Marksmanship = 58,
	Mechanical = 0,
	Explosives = 8,
	Medical = 12,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_44.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_44_Big.png",
	IsMercenary = true,
	Name = T(890000000005530, "Amina Yusuf") --[[ModItemUnitDataCompositeDef JAZZ_AME_44 Name]],
	Nick = T(890000000005531, "Amina") --[[ModItemUnitDataCompositeDef JAZZ_AME_44 Nick]],
	AllCapsNick = T(890000000005532, "AMINA") --[[ModItemUnitDataCompositeDef JAZZ_AME_44 AllCapsNick]],
	Bio = T(890000000005533, "Амина Юсуф бережёт хороший автомат и бинты в кармане — ветераны дольше живут, когда не стесняются собственной крови. Очереди короткие, взгляд холодный. Про неё говорят мало и уважительно — так безопаснее.") --[[ModItemUnitDataCompositeDef JAZZ_AME_44 Bio]],
	Nationality = "Nigeria",
	HireStatus = "NotMet",
	AMECategory = "Hardened",
	AMERole = "Autorifleman",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005534, "Я на линии. Говорите.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005535, "Работа есть — слушаю.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005536, "Контракт принят.") }) },
	MedicalDeposit = "none",
	StartingSalary = 450,
	StartingLevel = 1,
	StartingPerks = {
	"AutoWeapons",
	},
	Specialization = "Autoriflemen",
	MaxHitPoints = 80,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_44" }) },
	Equipment = { "Loot_JAZZ_AME_44" },
	gender = "Female",
	VoiceResponseId = "Jazz_AME_Female",
	FallbackMissingVR = "AnneLeMitrailleur",
	DaysUntilOnline = 0,
}
