UndefineClass('JAZZ_AME_53')
DefineClass.JAZZ_AME_53 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 66,
	Agility = 50,
	Dexterity = 52,
	Strength = 50,
	Wisdom = 82,
	Will = 28,
	Leadership = 65,
	Marksmanship = 38,
	Mechanical = 42,
	Explosives = 22,
	Medical = 30,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_53.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_53_Big.png",
	IsMercenary = true,
	Name = T(890000000005620, "Sgt. Nadia Okonkwo") --[[ModItemUnitDataCompositeDef JAZZ_AME_53 Name]],
	Nick = T(890000000005621, "Nadia") --[[ModItemUnitDataCompositeDef JAZZ_AME_53 Nick]],
	AllCapsNick = T(890000000005622, "NADIA") --[[ModItemUnitDataCompositeDef JAZZ_AME_53 AllCapsNick]],
	Bio = T(890000000005623, "A chipped wooden ruler draws Sergeant Nadia Okonkwo's sight lines in dust, on tables, or across a map. Teaching troops in Nigeria revealed that she diagnoses another shooter's mistake better than she displays perfection herself. Nadia's voice carries, but the lesson beneath it is precise and free of vanity. She cannot sustain every example demanded from younger bodies, yet pupils nearby soon stop snatching at the shot.") --[[ModItemUnitDataCompositeDef JAZZ_AME_53 Bio]],
	Nationality = "Nigeria",
	HireStatus = "NotMet",
	AMECategory = "Specialists",
	AMERole = "Instructor",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005624, "I'm available. We can discuss a contract.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005625, "Go ahead. Tell me what the job needs.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005626, "Understood. I will wait for your terms.") }) },
	MedicalDeposit = "none",
	StartingSalary = 243,
	StartingLevel = 1,
	StartingPerks = {
	"Teacher",
	},
	Specialization = "Leader",
	MaxHitPoints = 66,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_53" }) },
	Equipment = { "Loot_JAZZ_AME_53" },
	gender = "Female",
	VoiceResponseId = "Jazz_AME_Female",
	FallbackMissingVR = "AnneLeMitrailleur",
	DaysUntilOnline = 0,
}
