UndefineClass('Jazz_Eskimo')
DefineClass.Jazz_Eskimo = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AIM",
	Health = 97,
	Agility = 68,
	Dexterity = 70,
	Strength = 70,
	Wisdom = 55,
	Will = 60,
	Leadership = 25,
	Marksmanship = 95,
	Mechanical = 10,
	Explosives = 10,
	Medical = 15,
	Portrait = "Mod/Dv3mFVN/MercPortraits/Eskimo.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/Eskimo_Big.png",
	IsMercenary = true,
	Name = T(890000000004811, "[WIP] Эмиль «Эскимо» Кимос"),
	Nick = T(890000000004812, "Эскимо"),
	AllCapsNick = T(890000000004813, "ЭСКИМО"),
	Bio = T(890000000004814, "work in progress"),
	Nationality = "Arulco",
	Title = T(890000000004815, "Пленный снайпер"),
	Email = T(890000000004816, "Eskimo@arulco.reb"),
	snype_nick = T(890000000004817, "eskimo"),
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000004818, --[[ModItemUnitDataCompositeDef Jazz_Eskimo Text Offline ChatMessage voice:Jazz_Eskimo]] "Эскимо в камере... шучу. Перезвоните.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000004819, --[[ModItemUnitDataCompositeDef Jazz_Eskimo Text GreetingAndOffer ChatMessage voice:Jazz_Eskimo]] "Эскимо на связи. Свободен и рад этому.") }) },
	ConversationRestart = { PlaceObj('ChatMessage', { 'Text', T(890000000004820, --[[ModItemUnitDataCompositeDef Jazz_Eskimo Text ConversationRestart ChatMessage voice:Jazz_Eskimo]] "Связь прервалась. Вернёмся к делу.") }) },
	IdleLine = { PlaceObj('ChatMessage', { 'Text', T(890000000004821, --[[ModItemUnitDataCompositeDef Jazz_Eskimo Text IdleLine ChatMessage voice:Jazz_Eskimo]] "Холодно только в имени.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000004822, --[[ModItemUnitDataCompositeDef Jazz_Eskimo Text PartingWords ChatMessage voice:Jazz_Eskimo]] "Спасибо за свободу. Я в деле.") }) },
	RehireIntro = { PlaceObj('ChatMessage', { 'Text', T(890000000004823, --[[ModItemUnitDataCompositeDef Jazz_Eskimo Text RehireIntro ChatMessage voice:Jazz_Eskimo]] "Контракт заканчивается. Продлеваем?") }) },
	RehireOutro = { PlaceObj('ChatMessage', { 'Text', T(890000000004824, --[[ModItemUnitDataCompositeDef Jazz_Eskimo Text RehireOutro ChatMessage voice:Jazz_Eskimo]] "Остаюсь. Тюрьма научила меня терпению.") }) },
	MedicalDeposit = "none",
	StartingSalary = 400,
	SalaryIncrease = 150,
	SalaryLv1 = 150,
	SalaryMaxLv = 1500,
	StartingLevel = 3,
	CustomEquipGear = function (self, items)
	self:TryEquip(items, "Handheld A", "Firearm")
	self:TryEquip(items, "Handheld B", "Firearm")
	end,
	MaxHitPoints = 97,
	StartingPerks = {
	"Jazz_Perk_Eskimo",
	"Stealthy",
	"SteadyBreathing",
	"TrueGrit",
	},
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "Eskimo" }) },
	Equipment = { "Loot_JAZZ_Eskimo" },
	Tier = "Regular",
	Specialization = "Marksmen",
	pollyvoice = "Matthew",
	gender = "Male",
	VoiceResponseId = "Jazz_Eskimo",
	FallbackMissingVR = "Ice",
	DaysUntilOnline = 0,
}
