UndefineClass('JAZZ_AME_28')
DefineClass.JAZZ_AME_28 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 86,
	Agility = 56,
	Dexterity = 58,
	Strength = 74,
	Wisdom = 46,
	Will = 30,
	Leadership = 5,
	Marksmanship = 50,
	Mechanical = 0,
	Explosives = 5,
	Medical = 0,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_28.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_28_Big.png",
	IsMercenary = true,
	Name = T(890000000005370, "Pascal Ngoma") --[[ModItemUnitDataCompositeDef JAZZ_AME_28 Name]],
	Nick = T(890000000005371, "Pascal") --[[ModItemUnitDataCompositeDef JAZZ_AME_28 Nick]],
	AllCapsNick = T(890000000005372, "PASCAL") --[[ModItemUnitDataCompositeDef JAZZ_AME_28 AllCapsNick]],
	Bio = T(890000000005373, "Паскаль Нгома держал огневую точку в Гранд-Шьен с характером человека, который не любит бегать. Тяжёлый, упрямый: закрывает сектор и ждёт, пока сектор перестанет шевелиться. Под огнём не дёргается первым — и этим уже выигрывает время для остальных.") --[[ModItemUnitDataCompositeDef JAZZ_AME_28 Bio]],
	Nationality = "GrandChien",
	HireStatus = "NotMet",
	AMECategory = "Fighters",
	AMERole = "Machinegunner",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005374, "Дозвонился. Слушаю.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005375, "Ищу работу. Что предлагаете?") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005376, "До связи.") }) },
	MedicalDeposit = "none",
	StartingSalary = 104,
	StartingLevel = 1,
	StartingPerks = {
	"HeavyWeaponsTraining",
	},
	Specialization = "HeavyWeapons",
	MaxHitPoints = 86,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_28" }) },
	Equipment = { "Loot_JAZZ_AME_28" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Low",
	FallbackMissingVR = "LegionRaider",
	DaysUntilOnline = 0,
}
