UndefineClass('JAZZ_AME_46')
DefineClass.JAZZ_AME_46 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 92,
	Agility = 60,
	Dexterity = 58,
	Strength = 92,
	Wisdom = 34,
	Will = 60,
	Leadership = 5,
	Marksmanship = 56,
	Mechanical = 0,
	Explosives = 8,
	Medical = 5,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_46.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_46_Big.png",
	IsMercenary = true,
	Name = T(890000000005550, "Kofi Mensah") --[[ModItemUnitDataCompositeDef JAZZ_AME_46 Name]],
	Nick = T(890000000005551, "Kofi") --[[ModItemUnitDataCompositeDef JAZZ_AME_46 Nick]],
	AllCapsNick = T(890000000005552, "KOFI") --[[ModItemUnitDataCompositeDef JAZZ_AME_46 AllCapsNick]],
	Bio = T(890000000005553, "Кофи Менса из Ганы — силач: здоровье и мощь замечают раньше, чем меткость. Не догоняет — занимает место и делает его непригодным для врага. Там, где нужна тяжесть, а не грация, он уместен.") --[[ModItemUnitDataCompositeDef JAZZ_AME_46 Bio]],
	Nationality = "Ghana",
	HireStatus = "NotMet",
	AMECategory = "Hardened",
	AMERole = "Machinegunner",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005554, "Я на линии. Говорите.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005555, "Работа есть — слушаю.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005556, "Контракт принят.") }) },
	MedicalDeposit = "none",
	StartingSalary = 490,
	StartingLevel = 1,
	StartingPerks = {
	"HeavyWeaponsTraining",
	},
	Specialization = "HeavyWeapons",
	MaxHitPoints = 92,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_46" }) },
	Equipment = { "Loot_JAZZ_AME_46" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Hard",
	FallbackMissingVR = "ArmySoldier",
	DaysUntilOnline = 0,
}
