UndefineClass('Jazz_Hitman')
DefineClass.Jazz_Hitman = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AIM",
	Health = 80,
	Agility = 76,
	Dexterity = 78,
	Strength = 77,
	Wisdom = 59,
	Will = 37,
	Leadership = 16,
	Marksmanship = 93,
	Mechanical = 44,
	Explosives = 34,
	Medical = 10,
	Portrait = "Mod/Dv3mFVN/MercPortraits/Hitman.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/Hitman_Big.png",
	IsMercenary = true,
	Name = T(890000000004683, "Ричард Рутвен"),
	Nick = T(890000000004684, "Слай"),
	AllCapsNick = T(890000000004685, "СЛАЙ"),
	Bio = T(890000000004686, "Мистер Рутвен повстречался организации в Арулько, будучи разыскиваемым Интерполом за серию заказных убийств, сделанных с дальнего расстояния из снайперской винтовки. Охотник за головами, который передал организации заказ на него, настаивал на передаче ему отделенной от тела головы. Мистер Рутвен с таким подходом естественно не согласился и сделал встречное предложение - поработать на AIM."),
	Nationality = "USA",
	Title = T(890000000004687, "Wanted by Interpol"),
	Email = T(890000000004688, "Slay@dark.net"),
	snype_nick = T(890000000004689, "terry"),
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000004690, --[[ModItemUnitDataCompositeDef Jazz_Hitman Text Offline ChatMessage voice:Jazz_Hitman]] "Hitman offline.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000004691, --[[ModItemUnitDataCompositeDef Jazz_Hitman Text GreetingAndOffer ChatMessage voice:Jazz_Hitman]] "Говори быстро.") }) },
	ConversationRestart = { PlaceObj('ChatMessage', { 'Text', T(890000000004692, --[[ModItemUnitDataCompositeDef Jazz_Hitman Text ConversationRestart ChatMessage voice:Jazz_Hitman]] "Связь прервалась. Вернёмся к делу.") }) },
	IdleLine = { PlaceObj('ChatMessage', { 'Text', T(890000000004693, --[[ModItemUnitDataCompositeDef Jazz_Hitman Text IdleLine ChatMessage voice:Jazz_Hitman]] "Время идёт.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000004694, --[[ModItemUnitDataCompositeDef Jazz_Hitman Text PartingWords ChatMessage voice:Jazz_Hitman]] "Неделя. Не больше.") }) },
	RehireIntro = { PlaceObj('ChatMessage', { 'Text', T(890000000004695, --[[ModItemUnitDataCompositeDef Jazz_Hitman Text RehireIntro ChatMessage voice:Jazz_Hitman]] "Контракт заканчивается. Продлеваем?") }) },
	RehireOutro = { PlaceObj('ChatMessage', { 'Text', T(890000000004696, --[[ModItemUnitDataCompositeDef Jazz_Hitman Text RehireOutro ChatMessage voice:Jazz_Hitman]] "Остаюсь ещё немного.") }) },
	MedicalDeposit = "none",
	StartingSalary = 1500,
	SalaryIncrease = 150,
	SalaryLv1 = 600,
	SalaryMaxLv = 3000,
	StartingLevel = 4,
	CustomEquipGear = function (self, items)
	self:TryEquip(items, "Handheld A", "Firearm")
	self:TryEquip(items, "Handheld B", "Firearm")
	end,
	MaxHitPoints = 78,
	StartingPerks = {
	"Jazz_Perk_Hitman",
	"TakeAim",
	"SteadyBreathing",
	"DedicatedCamper",
	},
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "Jazz_Hitman" }) },
	Equipment = { "Loot_JAZZ_Hitman" },
	Tier = "Veteran",
	Specialization = "Marksmen",
	pollyvoice = "Matthew",
	gender = "Male",
	VoiceResponseId = "Jazz_Hitman",
	FallbackMissingVR = "Ice",
	DaysUntilOnline = 0,
}
