UndefineClass('JAZZ_AME_44')
DefineClass.JAZZ_AME_44 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 80,
	Agility = 70,
	Dexterity = 68,
	Strength = 64,
	Wisdom = 52,
	Will = 54,
	Leadership = 16,
	Marksmanship = 58,
	Mechanical = 0,
	Explosives = 8,
	Medical = 12,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_44.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_44_Big.png",
	IsMercenary = true,
	Name = T(890000000005530, "Amina Yusuf") --[[ModItemUnitDataCompositeDef JAZZ_AME_44 Name]],
	Nick = T(890000000005531, "Amina") --[[ModItemUnitDataCompositeDef JAZZ_AME_44 Nick]],
	AllCapsNick = T(890000000005532, "AMINA") --[[ModItemUnitDataCompositeDef JAZZ_AME_44 AllCapsNick]],
	Bio = T(890000000005533, "Spare bandages stay sealed in Amina Yusuf's waxed paper and are inspected whenever rain enters the seams. Nigerian service taught her that ammunition, sleep, and clean cloth all require conservation. Amina treats her rifle as a duty rather than a companion and keeps every burst brief. Her reserve feels severe across a table, but beside blood it becomes the steady distance needed to help.") --[[ModItemUnitDataCompositeDef JAZZ_AME_44 Bio]],
	Nationality = "Nigeria",
	HireStatus = "NotMet",
	AMECategory = "Hardened",
	AMERole = "Autorifleman",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005534, "I'm here. Talk.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005535, "If there's work, I'm listening.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005536, "Send the terms.") }) },
	MedicalDeposit = "none",
	StartingSalary = 123,
	StartingLevel = 1,
	StartingPerks = {
	"AutoWeapons",
	},
	Specialization = "Autoriflemen",
	MaxHitPoints = 80,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_44" }) },
	Equipment = { "Loot_JAZZ_AME_44" },
	gender = "Female",
	VoiceResponseId = "Jazz_AME_Female",
	FallbackMissingVR = "AnneLeMitrailleur",
	DaysUntilOnline = 0,
}
