UndefineClass('JAZZ_AME_34')
DefineClass.JAZZ_AME_34 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 90,
	Agility = 56,
	Dexterity = 54,
	Strength = 80,
	Wisdom = 44,
	Will = 34,
	Leadership = 5,
	Marksmanship = 48,
	Mechanical = 0,
	Explosives = 0,
	Medical = 0,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_34.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_34_Big.png",
	IsMercenary = true,
	Name = T(890000000005430, "Emeka Nwosu") --[[ModItemUnitDataCompositeDef JAZZ_AME_34 Name]],
	Nick = T(890000000005431, "Emeka") --[[ModItemUnitDataCompositeDef JAZZ_AME_34 Nick]],
	AllCapsNick = T(890000000005432, "EMEKA") --[[ModItemUnitDataCompositeDef JAZZ_AME_34 AllCapsNick]],
	Bio = T(890000000005433, "Эмека Нвосу — силач с нигерийским характером: здоровье и упрямство у него заметнее меткости, и он не стесняется этого. Про него шутят, что его проще нанять, чем сдвинуть. Он не возражает — лишь бы платили вовремя.") --[[ModItemUnitDataCompositeDef JAZZ_AME_34 Bio]],
	Nationality = "Nigeria",
	HireStatus = "NotMet",
	AMECategory = "Fighters",
	AMERole = "Machinegunner",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005434, "Дозвонился. Слушаю.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005435, "Ищу работу. Что предлагаете?") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005436, "До связи.") }) },
	MedicalDeposit = "none",
	StartingSalary = 107,
	StartingLevel = 1,
	StartingPerks = {
	"HeavyWeaponsTraining",
	"AutoWeapons",
	},
	Specialization = "HeavyWeapons",
	MaxHitPoints = 90,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_34" }) },
	Equipment = { "Loot_JAZZ_AME_34" },
	gender = "Male",
	VoiceResponseId = "IMP_male_01",
	FallbackMissingVR = "IMP_male_01",
	DaysUntilOnline = 0,
}
