UndefineClass('Jazz_Grace')
DefineClass.Jazz_Grace = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AIM",
	Health = 70,
	Agility = 75,
	Dexterity = 77,
	Strength = 67,
	Wisdom = 65,
	Will = 45,
	Leadership = 62,
	Marksmanship = 69,
	Mechanical = 20,
	Explosives = 20,
	Medical = 25,
	Portrait = "Mod/Dv3mFVN/MercPortraits/Grace.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/Grace_Big.png",
	IsMercenary = true,
	Name = T(890000000004747, "Грациелла «Грейс» Джирелли"),
	Nick = T(890000000004748, "Грейс"),
	AllCapsNick = T(890000000004749, "ГРЕЙС"),
	Bio = T(890000000004750, "Wildfire. Итальянка, записанная американкой. Боится тараканов, пессимистка. Средние статы броска (Сила 67, Меткость 69, Ловкость рук 77), Лидерство 62. Любит Аллика; недолюбливает Реда, Рикошета и Лаву."),
	Nationality = "USA",
	Title = T(890000000004751, "Итальянка"),
	Email = T(890000000004752, "Grace@aim.com"),
	snype_nick = T(890000000004753, "grace"),
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000004754, --[[ModItemUnitDataCompositeDef Jazz_Grace Text Offline ChatMessage voice:Jazz_Grace]] "Вы позвонили Грейс Джирелли, оставьте свое сообщение. Мама, если это ты... Да, я в порядке, и... нет, у меня нет времени для встречи с очередным милым молодым человеком. Я тебя люблю. Чао!") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000004755, --[[ModItemUnitDataCompositeDef Jazz_Grace Text GreetingAndOffer ChatMessage voice:Jazz_Grace]] "Говорит Грейс Джирелли.") }) },
	ConversationRestart = { PlaceObj('ChatMessage', { 'Text', T(890000000004756, --[[ModItemUnitDataCompositeDef Jazz_Grace Text ConversationRestart ChatMessage voice:Jazz_Grace]] "Я сказала...") }) },
	IdleLine = { PlaceObj('ChatMessage', { 'Text', T(890000000004757, --[[ModItemUnitDataCompositeDef Jazz_Grace Text IdleLine ChatMessage voice:Jazz_Grace]] "Кстати, я здорово управляюсь с ножами...") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000004758, --[[ModItemUnitDataCompositeDef Jazz_Grace Text PartingWords ChatMessage voice:Jazz_Grace]] "Прекрасно. Берегитесь, плохиши, кто не спрятался, я не виновата!") }) },
	RehireIntro = { PlaceObj('ChatMessage', { 'Text', T(890000000004759, --[[ModItemUnitDataCompositeDef Jazz_Grace Text RehireIntro ChatMessage voice:Jazz_Grace]] "Срок моего контракта истек, но я могу остаться, пупсик, если без меня вы не справитесь.") }) },
	RehireOutro = { PlaceObj('ChatMessage', { 'Text', T(890000000004760, --[[ModItemUnitDataCompositeDef Jazz_Grace Text RehireOutro ChatMessage voice:Jazz_Grace]] "Понято и принято.") }) },
	MedicalDeposit = "small",
	StartingSalary = 1600,
	SalaryIncrease = 150,
	SalaryLv1 = 600,
	SalaryMaxLv = 4000,
	StartingLevel = 3,
	CustomEquipGear = function (self, items)
	self:TryEquip(items, "Handheld A", "Firearm")
	self:TryEquip(items, "Handheld B", "Firearm")
	end,
	MaxHitPoints = 70,
	StartingPerks = {
	"Jazz_Perk_Grace",
	"Throwing",
	"Pessimist",
	"FirstThrow",
	},
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "Grace" }) },
	Equipment = { "Loot_JAZZ_Grace" },
	Tier = "Regular",
	Specialization = "Melee",
	pollyvoice = "Amy",
	gender = "Female",
	VoiceResponseId = "Jazz_Grace",
	FallbackMissingVR = "Ice",
	DaysUntilOnline = 0,
}
