UndefineClass('JAZZ_AME_26')
DefineClass.JAZZ_AME_26 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 78,
	Agility = 64,
	Dexterity = 64,
	Strength = 60,
	Wisdom = 50,
	Will = 28,
	Leadership = 8,
	Marksmanship = 54,
	Mechanical = 0,
	Explosives = 0,
	Medical = 5,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_26.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_26_Big.png",
	IsMercenary = true,
	Name = T(890000000005350, "Andile Nkosi") --[[ModItemUnitDataCompositeDef JAZZ_AME_26 Name]],
	Nick = T(890000000005351, "Andile") --[[ModItemUnitDataCompositeDef JAZZ_AME_26 Nick]],
	AllCapsNick = T(890000000005352, "ANDILE") --[[ModItemUnitDataCompositeDef JAZZ_AME_26 AllCapsNick]],
	Bio = T(890000000005353, "Blue electrical tape around Andile Nkosi's sling bears the plate number of the first truck he brought through untouched. South African convoy work taught him that careless fire could ruin cargo before an attacker reached it. Andile prefers routine, short instructions, and people who keep their hands to themselves. Sudden improvisation can leave him behind, but a revealed pattern brings disciplined restraint back to his weapon.") --[[ModItemUnitDataCompositeDef JAZZ_AME_26 Bio]],
	Nationality = "SouthAfrica",
	HireStatus = "NotMet",
	AMECategory = "Fighters",
	AMERole = "Autorifleman",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005354, "On the line.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005355, "I'm listening. Tell me about the job.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005356, "Understood. I'll be here.") }) },
	MedicalDeposit = "none",
	StartingSalary = 87,
	StartingLevel = 1,
	StartingPerks = {
	"AutoWeapons",
	},
	Specialization = "Autoriflemen",
	MaxHitPoints = 78,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_26" }) },
	Equipment = { "Loot_JAZZ_AME_26" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Hard",
	FallbackMissingVR = "ArmySoldier",
	DaysUntilOnline = 0,
}
