UndefineClass('JAZZ_AME_52')
DefineClass.JAZZ_AME_52 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 68,
	Agility = 48,
	Dexterity = 50,
	Strength = 52,
	Wisdom = 85,
	Will = 32,
	Leadership = 68,
	Marksmanship = 35,
	Mechanical = 50,
	Explosives = 28,
	Medical = 35,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_52.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_52_Big.png",
	IsMercenary = true,
	Name = T(890000000005610, "Captain Amara Koné") --[[ModItemUnitDataCompositeDef JAZZ_AME_52 Name]],
	Nick = T(890000000005611, "Amara") --[[ModItemUnitDataCompositeDef JAZZ_AME_52 Nick]],
	AllCapsNick = T(890000000005612, "AMARA") --[[ModItemUnitDataCompositeDef JAZZ_AME_52 AllCapsNick]],
	Bio = T(890000000005613, "Капитан Амара Коне — инструктор из Мали с учительским характером. Учит жёстко, без театра: оставляет объяснения, которые потом спасают жизни. Считает, что один хороший учитель дешевле десяти свежих могил.") --[[ModItemUnitDataCompositeDef JAZZ_AME_52 Bio]],
	Nationality = "Mali",
	HireStatus = "NotMet",
	AMECategory = "Specialists",
	AMERole = "Instructor",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005614, "На связи. Готов обсуждать контракт.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005615, "Слушаю. Расскажите о задаче.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005616, "До связи.") }) },
	MedicalDeposit = "none",
	StartingSalary = 264,
	StartingLevel = 1,
	StartingPerks = {
	"Teacher",
	},
	Specialization = "Leader",
	MaxHitPoints = 68,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_52" }) },
	Equipment = { "Loot_JAZZ_AME_52" },
	gender = "Female",
	VoiceResponseId = "Jazz_AME_Female",
	FallbackMissingVR = "AnneLeMitrailleur",
	DaysUntilOnline = 0,
}
