UndefineClass('JAZZ_AME_36')
DefineClass.JAZZ_AME_36 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 78,
	Agility = 64,
	Dexterity = 62,
	Strength = 58,
	Wisdom = 52,
	Will = 28,
	Leadership = 5,
	Marksmanship = 54,
	Mechanical = 15,
	Explosives = 0,
	Medical = 5,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_36.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_36_Big.png",
	IsMercenary = true,
	Name = T(890000000005450, "Mamadou Traoré") --[[ModItemUnitDataCompositeDef JAZZ_AME_36 Name]],
	Nick = T(890000000005451, "Mamadou") --[[ModItemUnitDataCompositeDef JAZZ_AME_36 Nick]],
	AllCapsNick = T(890000000005452, "MAMADOU") --[[ModItemUnitDataCompositeDef JAZZ_AME_36 AllCapsNick]],
	Bio = T(890000000005453, "A mismatched screwdriver wrapped in red cloth shares Mamadou Traoré's pocket with a wire cutter. He began tending other men's weapons during quiet hours on a Malian road patrol. No gifted engineer, Mamadou simply remembers which small part caused trouble last time. Machinery yields to repetition rather than insight for him, but uncomplicated faults tend to stay fixed once his careful hands have visited.") --[[ModItemUnitDataCompositeDef JAZZ_AME_36 Bio]],
	Nationality = "Mali",
	HireStatus = "NotMet",
	AMECategory = "Fighters",
	AMERole = "Autorifleman",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005454, "On the line.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005455, "I'm listening. Tell me about the job.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005456, "Understood. I'll be here.") }) },
	MedicalDeposit = "none",
	StartingSalary = 84,
	StartingLevel = 1,
	StartingPerks = {
	"AutoWeapons",
	},
	Specialization = "Autoriflemen",
	MaxHitPoints = 78,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_36" }) },
	Equipment = { "Loot_JAZZ_AME_36" },
	gender = "Male",
	VoiceResponseId = "PierreMerc",
	FallbackMissingVR = "PierreMerc",
	DaysUntilOnline = 0,
}
