UndefineClass('JAZZ_Legion_LeaderT2_Lieutenant')
DefineClass.JAZZ_Legion_LeaderT2_Lieutenant = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",


	comment = "Т2 Командир Lieutenant | Командир-Стрелок",
	object_class = "UnitData",
	Health = 90,
	Agility = 85,
	Dexterity = 85,
	Strength = 80,
	Wisdom = 70,
	Will = 90,
	Leadership = 80,
	Marksmanship = 88,
	Mechanical = 100,
	Explosives = 50,
	Medical = 50,
	Portrait = "UI/EnemiesPortraits/LegionOfficer",
	BigPortrait = "UI/Enemies/LegionRaider",
	Name = T(786423367133, --[[ModItemUnitDataCompositeDef JAZZ_Legion_LeaderT2_Lieutenant Name]] "Командир"),
	Randomization = true,
	elite = true,
	eliteCategory = "Legion",
	Affiliation = "Legion",
	StartingLevel = 7,
	villain = true,
	neutral_retaliate = true,
	AIKeywords = {
		"Control",
		"Smoke",
		"Explosives",
		"Soldier",
		"Ordnance",
		"Leader",
	},
	archetype = "Legion_Frontliner",
	role = "Commander",
	RepositionArchetype = "Legion_Frontliner",
	AlwaysUseOpeningAttack = true,
	OpeningAttackType = "Overwatch",
	MaxAttacks = 10,
	PickCustomArchetype = function (self, proto_context)
		return JazzAI_PickCombatStance(self, proto_context)
	end,
	CustomEquipGear = function (self, items)  end,
	MaxHitPoints = 80,
	StartingPerks = {
		"CQCTraining",
		"Spiritual",
		"BattleFocus",
		"RelentlessAdvance",
		"ShoulderToShoulder",
		"AutoWeapons",
		"Spotter",
		"SidneyPerk",
		"TakeAim",
		"OnMyTarget",
		"Ironclad",
		"LightStep",
		"TrickShot",
		"LeadFromTheFront",
		"Hobbler",
		"LightningReactionNPC",
		"StressManagement",
		"Hotblood",
		"Instagib",
		"HitTheDeck",
		"CollateralDamage",
	},
	AppearancesList = {
		PlaceObj('AppearanceWeight', {
			'Preset', "Legion_Shaman",
		}),
		PlaceObj('AppearanceWeight', {
			'Preset', "Legion_Shaman02",
		}),
		PlaceObj('AppearanceWeight', {
			'Preset', "Legion_Shaman03",
		}),
		PlaceObj('AppearanceWeight', {
			'Preset', "LegionRaidLeader_Stronger",
			'Weight', 4,
		}),
		PlaceObj('AppearanceWeight', {
			'Preset', "LegionRaidLeader_Stronger_alt",
			'Weight', 4,
		}),
		PlaceObj('AppearanceWeight', {
			'Preset', "LegionRaidLeader_Stronger_alt_2",
			'Weight', 4,
		}),
	},
	Equipment = {
		"Lieutenant_Inventory",
	},
	AdditionalGroups = {
		PlaceObj('AdditionalGroup', {
			'Weight', 50,
			'Exclusive', true,
			'Name', "LegionMale_1",
		}),
		PlaceObj('AdditionalGroup', {
			'Weight', 50,
			'Exclusive', true,
			'Name', "LegionMale_2",
		}),
	},
	pollyvoice = "Joey",
	gender = "Male",
	VoiceResponseId = "LegionRaider",
}

