UndefineClass('JAZZ_AME_39')
DefineClass.JAZZ_AME_39 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 84,
	Agility = 70,
	Dexterity = 68,
	Strength = 72,
	Wisdom = 44,
	Will = 55,
	Leadership = 12,
	Marksmanship = 54,
	Mechanical = 0,
	Explosives = 10,
	Medical = 8,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_39.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_39_Big.png",
	IsMercenary = true,
	Name = T(890000000005480, "Joseph Mukendi") --[[ModItemUnitDataCompositeDef JAZZ_AME_39 Name]],
	Nick = T(890000000005481, "Hyena") --[[ModItemUnitDataCompositeDef JAZZ_AME_39 Nick]],
	AllCapsNick = T(890000000005482, "HYENA") --[[ModItemUnitDataCompositeDef JAZZ_AME_39 AllCapsNick]],
	Bio = T(890000000005483, "Жозефа Мукенди в Гранд-Шьен зовут «Гиена»: годами делал засады так, что жертвы узнавали кличку раньше лица. В тесноте бьёт грязно и быстро — красивой стрельбы меньше, зато чаще остаётся живым. Нервы держат. Знает себе цену и не любит, когда её занижают.") --[[ModItemUnitDataCompositeDef JAZZ_AME_39 Bio]],
	Nationality = "GrandChien",
	HireStatus = "NotMet",
	AMECategory = "Hardened",
	AMERole = "Autorifleman",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005484, "Я на линии. Говорите.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005485, "Работа есть — слушаю.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005486, "Контракт принят.") }) },
	MedicalDeposit = "none",
	StartingSalary = 127,
	StartingLevel = 1,
	StartingPerks = {
	"AutoWeapons",
	"CQCTraining",
	},
	Specialization = "Autoriflemen",
	MaxHitPoints = 84,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_39" }) },
	Equipment = { "Loot_JAZZ_AME_39" },
	gender = "Male",
	VoiceResponseId = "IMP_male_01",
	FallbackMissingVR = "IMP_male_01",
	DaysUntilOnline = 0,
}
