UndefineClass('JAZZ_AME_57')
DefineClass.JAZZ_AME_57 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 70,
	Agility = 48,
	Dexterity = 52,
	Strength = 55,
	Wisdom = 60,
	Will = 26,
	Leadership = 8,
	Marksmanship = 24,
	Mechanical = 50,
	Explosives = 68,
	Medical = 8,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_57.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_57_Big.png",
	IsMercenary = true,
	Name = T(890000000005660, "Bakary Diarra") --[[ModItemUnitDataCompositeDef JAZZ_AME_57 Name]],
	Nick = T(890000000005661, "Bakary") --[[ModItemUnitDataCompositeDef JAZZ_AME_57 Nick]],
	AllCapsNick = T(890000000005662, "BAKARY") --[[ModItemUnitDataCompositeDef JAZZ_AME_57 AllCapsNick]],
	Bio = T(890000000005663, "A cotton-lined cigarette tin holds Bakary Diarra's detonators and receives a nervous tap before work. He acquired them by trading away his pistol during years handling Malian road charges. Wires obey sequence while gunfire does not, a distinction Bakary takes seriously. Beside a device he understands he is composed, but uncontrolled danger exposes how much confidence depends on preparing the ground himself.") --[[ModItemUnitDataCompositeDef JAZZ_AME_57 Bio]],
	Nationality = "Mali",
	HireStatus = "NotMet",
	AMECategory = "Specialists",
	AMERole = "Sapper",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005664, "I'm available. We can discuss a contract.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005665, "Go ahead. Tell me what the job needs.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005666, "Understood. I will wait for your terms.") }) },
	MedicalDeposit = "none",
	StartingSalary = 171,
	StartingLevel = 1,
	StartingPerks = {
	"Throwing",
	},
	Specialization = "ExplosiveExpert",
	MaxHitPoints = 70,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_57" }) },
	Equipment = { "Loot_JAZZ_AME_57" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Hard",
	FallbackMissingVR = "ArmySoldier",
	DaysUntilOnline = 0,
}
