UndefineClass('JAZZ_AME_58')
DefineClass.JAZZ_AME_58 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 72,
	Agility = 50,
	Dexterity = 54,
	Strength = 54,
	Wisdom = 62,
	Will = 28,
	Leadership = 6,
	Marksmanship = 26,
	Mechanical = 52,
	Explosives = 66,
	Medical = 10,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_58.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_58_Big.png",
	IsMercenary = true,
	Name = T(890000000005670, "Marie-Claire Mbala") --[[ModItemUnitDataCompositeDef JAZZ_AME_58 Name]],
	Nick = T(890000000005671, "Marie") --[[ModItemUnitDataCompositeDef JAZZ_AME_58 Nick]],
	AllCapsNick = T(890000000005672, "MARIE") --[[ModItemUnitDataCompositeDef JAZZ_AME_58 AllCapsNick]],
	Bio = T(890000000005673, "Мари-Клер Мбала ставит мины в Конго без лишней поэзии. Взрывчатка для неё важнее патронов, и она это повторяет всем новичкам. Бросок уверенный, характер сухой — сначала любопытство, потом осторожность.") --[[ModItemUnitDataCompositeDef JAZZ_AME_58 Bio]],
	Nationality = "Congo",
	HireStatus = "NotMet",
	AMECategory = "Specialists",
	AMERole = "Sapper",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005674, "На связи. Готов обсуждать контракт.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005675, "Слушаю. Расскажите о задаче.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005676, "До связи.") }) },
	MedicalDeposit = "none",
	StartingSalary = 214,
	StartingLevel = 1,
	StartingPerks = {
	"Throwing",
	},
	Specialization = "ExplosiveExpert",
	MaxHitPoints = 72,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_58" }) },
	Equipment = { "Loot_JAZZ_AME_58" },
	gender = "Female",
	VoiceResponseId = "Jazz_AME_Female",
	FallbackMissingVR = "AnneLeMitrailleur",
	DaysUntilOnline = 0,
}
