UndefineClass('Jazz_Lucky')
DefineClass.Jazz_Lucky = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AIM",
	Health = 78,
	Agility = 75,
	Dexterity = 75,
	Strength = 75,
	Wisdom = 70,
	Will = 55,
	Leadership = 58,
	Marksmanship = 88,
	Mechanical = 30,
	Explosives = 25,
	Medical = 25,
	Portrait = "Mod/Dv3mFVN/MercPortraits/Lucky.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/Lucky_Big.png",
	IsMercenary = true,
	Name = T(890000000004779, "[WIP] Люк «Лаки» Фабр"),
	Nick = T(890000000004780, "Лаки"),
	AllCapsNick = T(890000000004781, "ЛАКИ"),
	Bio = T(890000000004782, "work in progress"),
	Nationality = "France",
	Title = T(890000000004783, "Бельгиец"),
	Email = T(890000000004784, "Lucky@aim.com"),
	snype_nick = T(890000000004785, "lucky"),
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000004786, --[[ModItemUnitDataCompositeDef Jazz_Lucky Text Offline ChatMessage voice:Jazz_Lucky]] "Это Люк Фабр, говорите, пожалуйста, после сигнала.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000004787, --[[ModItemUnitDataCompositeDef Jazz_Lucky Text GreetingAndOffer ChatMessage voice:Jazz_Lucky]] "Алло!") }) },
	ConversationRestart = { PlaceObj('ChatMessage', { 'Text', T(890000000004788, --[[ModItemUnitDataCompositeDef Jazz_Lucky Text ConversationRestart ChatMessage voice:Jazz_Lucky]] "Я сказал...") }) },
	IdleLine = { PlaceObj('ChatMessage', { 'Text', T(890000000004789, --[[ModItemUnitDataCompositeDef Jazz_Lucky Text IdleLine ChatMessage voice:Jazz_Lucky]] "Я - оружие массового поражения...") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000004790, --[[ModItemUnitDataCompositeDef Jazz_Lucky Text PartingWords ChatMessage voice:Jazz_Lucky]] "D'accord, я согласен.") }) },
	RehireIntro = { PlaceObj('ChatMessage', { 'Text', T(890000000004791, --[[ModItemUnitDataCompositeDef Jazz_Lucky Text RehireIntro ChatMessage voice:Jazz_Lucky]] "Мой контракт... Мы его продлеваем?") }) },
	RehireOutro = { PlaceObj('ChatMessage', { 'Text', T(890000000004792, --[[ModItemUnitDataCompositeDef Jazz_Lucky Text RehireOutro ChatMessage voice:Jazz_Lucky]] "D'accord. Я согласен.") }) },
	MedicalDeposit = "small",
	StartingSalary = 1900,
	SalaryIncrease = 150,
	SalaryLv1 = 700,
	SalaryMaxLv = 4500,
	StartingLevel = 4,
	CustomEquipGear = function (self, items)
	self:TryEquip(items, "Handheld A", "Firearm")
	self:TryEquip(items, "Handheld B", "Firearm")
	end,
	MaxHitPoints = 78,
	StartingPerks = {
	"Jazz_Perk_Lucky",
	"AutoWeapons",
	"MartialArts",
	"Hotblood",
	},
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "Lucky" }) },
	Equipment = { "Loot_JAZZ_Lucky" },
	Tier = "Veteran",
	Specialization = "Autoriflemen",
	pollyvoice = "Matthew",
	gender = "Male",
	VoiceResponseId = "Jazz_Lucky",
	FallbackMissingVR = "Ice",
	DaysUntilOnline = 0,
}
