UndefineClass('JAZZ_AME_36')
DefineClass.JAZZ_AME_36 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 78,
	Agility = 64,
	Dexterity = 62,
	Strength = 58,
	Wisdom = 52,
	Will = 28,
	Leadership = 5,
	Marksmanship = 54,
	Mechanical = 15,
	Explosives = 0,
	Medical = 5,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_36.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_36_Big.png",
	IsMercenary = true,
	Name = T(890000000005450, "Mamadou Traoré") --[[ModItemUnitDataCompositeDef JAZZ_AME_36 Name]],
	Nick = T(890000000005451, "Mamadou") --[[ModItemUnitDataCompositeDef JAZZ_AME_36 Nick]],
	AllCapsNick = T(890000000005452, "MAMADOU") --[[ModItemUnitDataCompositeDef JAZZ_AME_36 AllCapsNick]],
	Bio = T(890000000005453, "Мамаду Траоре из Мали чинит стволы соседей чаще, чем хвастается своими. Отвёртка часто чужая, зато руки помнят, куда крутить. После боя ещё и собирает то, что осталось стрелять.") --[[ModItemUnitDataCompositeDef JAZZ_AME_36 Bio]],
	Nationality = "Mali",
	HireStatus = "NotMet",
	AMECategory = "Fighters",
	AMERole = "Autorifleman",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005454, "Дозвонился. Слушаю.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005455, "Ищу работу. Что предлагаете?") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005456, "До связи.") }) },
	MedicalDeposit = "none",
	StartingSalary = 225,
	StartingLevel = 1,
	StartingPerks = {
	"AutoWeapons",
	},
	Specialization = "Autoriflemen",
	MaxHitPoints = 78,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_36" }) },
	Equipment = { "Loot_JAZZ_AME_36" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Low",
	FallbackMissingVR = "LegionRaider",
	DaysUntilOnline = 0,
}
