UndefineClass('JAZZ_AME_23')
DefineClass.JAZZ_AME_23 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 88,
	Agility = 58,
	Dexterity = 56,
	Strength = 78,
	Wisdom = 46,
	Will = 32,
	Leadership = 0,
	Marksmanship = 48,
	Mechanical = 0,
	Explosives = 0,
	Medical = 0,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_23.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_23_Big.png",
	IsMercenary = true,
	Name = T(890000000005320, "Chukwuemeka \"Emeka\" Obi") --[[ModItemUnitDataCompositeDef JAZZ_AME_23 Name]],
	Nick = T(890000000005321, "Emeka") --[[ModItemUnitDataCompositeDef JAZZ_AME_23 Nick]],
	AllCapsNick = T(890000000005322, "EMEKA") --[[ModItemUnitDataCompositeDef JAZZ_AME_23 AllCapsNick]],
	Bio = T(890000000005323, "Tea comes from Chukwuemeka “Emeka” Obi's shrapnel-dented tin cup, which nobody is allowed to repair. The dent outlived a Nigerian checkpoint erased after months behind its machine gun. Built for weight rather than delicacy, Emeka laughs first when a careful shot goes astray. He may not pick one point from the landscape elegantly, but knows how to make an entire stretch of ground feel unwelcoming.") --[[ModItemUnitDataCompositeDef JAZZ_AME_23 Bio]],
	Nationality = "Nigeria",
	HireStatus = "NotMet",
	AMECategory = "Fighters",
	AMERole = "Machinegunner",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005324, "On the line.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005325, "I'm listening. Tell me about the job.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005326, "Understood. I'll be here.") }) },
	MedicalDeposit = "none",
	StartingSalary = 101,
	StartingLevel = 1,
	StartingPerks = {
	"HeavyWeaponsTraining",
	"AutoWeapons",
	},
	Specialization = "HeavyWeapons",
	MaxHitPoints = 88,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_23" }) },
	Equipment = { "Loot_JAZZ_AME_23" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Low",
	FallbackMissingVR = "LegionRaider",
	DaysUntilOnline = 0,
}
