UndefineClass('JAZZ_AME_32')
DefineClass.JAZZ_AME_32 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 72,
	Agility = 68,
	Dexterity = 68,
	Strength = 50,
	Wisdom = 54,
	Will = 22,
	Leadership = 0,
	Marksmanship = 58,
	Mechanical = 0,
	Explosives = 0,
	Medical = 5,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_32.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_32_Big.png",
	IsMercenary = true,
	Name = T(890000000005410, "Awa Sow") --[[ModItemUnitDataCompositeDef JAZZ_AME_32 Name]],
	Nick = T(890000000005411, "Awa") --[[ModItemUnitDataCompositeDef JAZZ_AME_32 Nick]],
	AllCapsNick = T(890000000005412, "AWA") --[[ModItemUnitDataCompositeDef JAZZ_AME_32 AllCapsNick]],
	Bio = T(890000000005413, "The bent key to Awa Sow's vanished dockside job taps against her thigh whenever someone explains her own work to her. Its Senegalese storehouse had passages too narrow for grand gestures. Awa learned to slip around trouble quickly without enjoying the sound of its arrival. Sustained noise wears at her composure, but close walls give that speed somewhere useful to go.") --[[ModItemUnitDataCompositeDef JAZZ_AME_32 Bio]],
	Nationality = "Senegal",
	HireStatus = "NotMet",
	AMECategory = "Fighters",
	AMERole = "Rifle",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005414, "On the line.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005415, "I'm listening. Tell me about the job.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005416, "Understood. I'll be here.") }) },
	MedicalDeposit = "none",
	StartingSalary = 57,
	StartingLevel = 1,
	StartingPerks = {
	"Stealthy",
	},
	Specialization = "AllRounder",
	MaxHitPoints = 72,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_32" }) },
	Equipment = { "Loot_JAZZ_AME_32" },
	gender = "Female",
	VoiceResponseId = "IMP_female_01",
	FallbackMissingVR = "IMP_female_01",
	DaysUntilOnline = 0,
}
