UndefineClass('JAZZ_AME_22')
DefineClass.JAZZ_AME_22 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 76,
	Agility = 64,
	Dexterity = 64,
	Strength = 58,
	Wisdom = 52,
	Will = 28,
	Leadership = 5,
	Marksmanship = 54,
	Mechanical = 0,
	Explosives = 0,
	Medical = 5,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_22.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_22_Big.png",
	IsMercenary = true,
	Name = T(890000000005310, "Bastien Lafontaine") --[[ModItemUnitDataCompositeDef JAZZ_AME_22 Name]],
	Nick = T(890000000005311, "Bastien") --[[ModItemUnitDataCompositeDef JAZZ_AME_22 Nick]],
	AllCapsNick = T(890000000005312, "BASTIEN") --[[ModItemUnitDataCompositeDef JAZZ_AME_22 AllCapsNick]],
	Bio = T(890000000005313, "Bastien Lafontaine learned his trade with a Grand Chien militia, covering alleys where walls seemed to close in during trouble. Cheap tobacco stains his fingers, but he saves the cigarette until everything has gone quiet. A rolling paper stays folded inside the oil rag he uses on his rifle, a private promise of rest. Bastien is not imaginative under changing orders, yet in a confined street his steady bursts arrive exactly where companions expect them.") --[[ModItemUnitDataCompositeDef JAZZ_AME_22 Bio]],
	Nationality = "GrandChien",
	HireStatus = "NotMet",
	AMECategory = "Fighters",
	AMERole = "Autorifleman",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005314, "On the line.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005315, "I'm listening. Tell me about the job.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005316, "Understood. I'll be here.") }) },
	MedicalDeposit = "none",
	StartingSalary = 92,
	StartingLevel = 1,
	StartingPerks = {
	"AutoWeapons",
	},
	Specialization = "Autoriflemen",
	MaxHitPoints = 76,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_22" }) },
	Equipment = { "Loot_JAZZ_AME_22" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Hard",
	FallbackMissingVR = "ArmySoldier",
	DaysUntilOnline = 0,
}
