UndefineClass('Jazz_Steiger')
DefineClass.Jazz_Steiger = {
	Dislikes = {
					"Jazz_Cord",
					"Jazz_Bull",
				},
	Likes = {
					"Jazz_Laura",
					"Jazz_Henning",
					"Grunty",
				},
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AIM",
	Health = 80,
	Agility = 76,
	Dexterity = 87,
	Strength = 68,
	Wisdom = 90,
	Will = 72,
	Leadership = 69,
	Marksmanship = 94,
	Mechanical = 32,
	Explosives = 36,
	Medical = 46,
	Portrait = "Mod/Dv3mFVN/MercPortraits/Steiger.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/Steiger_Big.png",
	IsMercenary = true,
	Name = T(890000000004763, "Рудольф Штайгер"),
	Nick = T(890000000004764, "Рудольф"),
	AllCapsNick = T(890000000004765, "РУДОЛЬФ"),
	Bio = T(890000000004766, "У этого бывшего бойца GSG-9 есть только одна слабость... доктор Лора Колин, с которой он познакомился на курсах в Любеке. Он - настоящий профи. Его сильная сторона - ночные операции. Кроме того, он с километра бьет пулей белку в глаз. У него есть способности инструктора. Его манеры оставляют желать лучшего. Хорошо работает вместе с Хеннингом фон Браницем, но Дуг Милтон действует на него, как красная тряпка на быка."),
	Nationality = "Germany",
	Title = T(890000000004767, "Counter-Terrorist"),
	Email = T(890000000004768, "Steiger@aim.com"),
	snype_nick = T(890000000004769, "steiger"),
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000004770, --[[ModItemUnitDataCompositeDef Jazz_Steiger Text Offline ChatMessage voice:Jazz_Steiger]] "Говорит Рудольф Штайгер. Оставьте сообщение. Возможно, я перезвоню.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000004771, --[[ModItemUnitDataCompositeDef Jazz_Steiger Text GreetingAndOffer ChatMessage voice:Jazz_Steiger]] "Привет...") }) },
	ConversationRestart = { PlaceObj('ChatMessage', { 'Text', T(890000000004772, --[[ModItemUnitDataCompositeDef Jazz_Steiger Text ConversationRestart ChatMessage voice:Jazz_Steiger]] "Я сказал...") }) },
	IdleLine = { PlaceObj('ChatMessage', { 'Text', T(890000000004773, --[[ModItemUnitDataCompositeDef Jazz_Steiger Text IdleLine ChatMessage voice:Jazz_Steiger]] "Мне есть, чем заняться...") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000004774, --[[ModItemUnitDataCompositeDef Jazz_Steiger Text PartingWords ChatMessage voice:Jazz_Steiger]] "Отлично, уже еду.") }) },
	RehireIntro = { PlaceObj('ChatMessage', { 'Text', T(890000000004775, --[[ModItemUnitDataCompositeDef Jazz_Steiger Text RehireIntro ChatMessage voice:Jazz_Steiger]] "Заинтересован в продлении контракта? Я бы не отказался...") }) },
	RehireOutro = { PlaceObj('ChatMessage', { 'Text', T(890000000004776, --[[ModItemUnitDataCompositeDef Jazz_Steiger Text RehireOutro ChatMessage voice:Jazz_Steiger]] "Выпьем за долгое и взаимовыгодное сотрудничество...") }) },
	MedicalDeposit = "large",
	StartingSalary = 3600,
	SalaryIncrease = 240,
	SalaryLv1 = 2500,
	SalaryMaxLv = 11000,
	StartingLevel = 6,
	CustomEquipGear = function (self, items)
	self:TryEquip(items, "Handheld A", "Firearm")
	self:TryEquip(items, "Handheld B", "Firearm")
	end,
	MaxHitPoints = 80,
	StartingPerks = {
	"Jazz_Perk_Steiger",
	"NightOps",
	"Teacher",
	"LeadFromTheFront",
	},
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "Steiger" }) },
	Equipment = { "Loot_JAZZ_Steiger" },
	Tier = "Legendary",
	Specialization = "Leader",
	pollyvoice = "Matthew",
	gender = "Male",
	VoiceResponseId = "Jazz_Steiger",
	FallbackMissingVR = "Ice",
	DaysUntilOnline = 0,
}
