UndefineClass('JAZZ_AME_58')
DefineClass.JAZZ_AME_58 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 72,
	Agility = 50,
	Dexterity = 54,
	Strength = 54,
	Wisdom = 62,
	Will = 28,
	Leadership = 6,
	Marksmanship = 26,
	Mechanical = 52,
	Explosives = 66,
	Medical = 10,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_58.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_58_Big.png",
	IsMercenary = true,
	Name = T(890000000005670, "Marie-Claire Mbala") --[[ModItemUnitDataCompositeDef JAZZ_AME_58 Name]],
	Nick = T(890000000005671, "Marie") --[[ModItemUnitDataCompositeDef JAZZ_AME_58 Nick]],
	AllCapsNick = T(890000000005672, "MARIE") --[[ModItemUnitDataCompositeDef JAZZ_AME_58 AllCapsNick]],
	Bio = T(890000000005673, "A tailor's tape coils in Marie-Claire Mbala's left pocket, measuring fuse without trusting footsteps. Congolese quarry charges taught her that explosives reward plain measurement and punish romantic language. Her manner is dry, and every newcomer must identify the exit before touching a wire. Marie-Claire leans too close when puzzled, but once a device reveals its logic, hesitation no longer wastes anyone's time.") --[[ModItemUnitDataCompositeDef JAZZ_AME_58 Bio]],
	Nationality = "Congo",
	HireStatus = "NotMet",
	AMECategory = "Specialists",
	AMERole = "Sapper",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005674, "I'm available. We can discuss a contract.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005675, "Go ahead. Tell me what the job needs.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005676, "Understood. I will wait for your terms.") }) },
	MedicalDeposit = "none",
	StartingSalary = 214,
	StartingLevel = 1,
	StartingPerks = {
	"Throwing",
	},
	Specialization = "ExplosiveExpert",
	MaxHitPoints = 72,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_58" }) },
	Equipment = { "Loot_JAZZ_AME_58" },
	gender = "Female",
	VoiceResponseId = "Jazz_AME_Female",
	FallbackMissingVR = "AnneLeMitrailleur",
	DaysUntilOnline = 0,
}
