UndefineClass('JAZZ_AME_31')
DefineClass.JAZZ_AME_31 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 80,
	Agility = 64,
	Dexterity = 64,
	Strength = 62,
	Wisdom = 48,
	Will = 30,
	Leadership = 5,
	Marksmanship = 54,
	Mechanical = 0,
	Explosives = 0,
	Medical = 5,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_31.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_31_Big.png",
	IsMercenary = true,
	Name = T(890000000005400, "Rafael dos Santos") --[[ModItemUnitDataCompositeDef JAZZ_AME_31 Name]],
	Nick = T(890000000005401, "Rafael") --[[ModItemUnitDataCompositeDef JAZZ_AME_31 Nick]],
	AllCapsNick = T(890000000005402, "RAFAEL") --[[ModItemUnitDataCompositeDef JAZZ_AME_31 AllCapsNick]],
	Bio = T(890000000005403, "Рафаэль дос Сантос из Анголы учится медленнее иных, зато не ломается от первой тяжёлой недели. Очереди для него — ремесло, выученное кровью и пылью. Не обещает чудес. Обещает явиться трезвым и не бросить позицию без приказа.") --[[ModItemUnitDataCompositeDef JAZZ_AME_31 Bio]],
	Nationality = "Angola",
	HireStatus = "NotMet",
	AMECategory = "Fighters",
	AMERole = "Autorifleman",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005404, "Дозвонился. Слушаю.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005405, "Ищу работу. Что предлагаете?") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005406, "До связи.") }) },
	MedicalDeposit = "none",
	StartingSalary = 89,
	StartingLevel = 1,
	StartingPerks = {
	"AutoWeapons",
	},
	Specialization = "Autoriflemen",
	MaxHitPoints = 80,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_31" }) },
	Equipment = { "Loot_JAZZ_AME_31" },
	gender = "Male",
	VoiceResponseId = "IMP_male_01",
	FallbackMissingVR = "IMP_male_01",
	DaysUntilOnline = 0,
}
