UndefineClass('Jazz_Vilde')
DefineClass.Jazz_Vilde = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AIM",
	Health = 81,
	Agility = 82,
	Dexterity = 78,
	Strength = 79,
	Wisdom = 83,
	Will = 60,
	Leadership = 67,
	Marksmanship = 76,
	Mechanical = 37,
	Explosives = 23,
	Medical = 34,
	Portrait = "Mod/Dv3mFVN/MercPortraits/Vilde.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/Vilde_Big.png",
	IsMercenary = true,
	Name = T(890000000004731, "Леннарт Вильде «Зануда»"),
	Nick = T(890000000004732, "Зануда"),
	AllCapsNick = T(890000000004733, "ЗАНУДА"),
	Bio = T(890000000004734, "Леннарт по своей природе лидер, и его уверенность заразительна. Чувство юмора, напротив, оставляет желать лучшего. Как и Янно Аллик, он сам родом из Эстонии, и у него мать-немка. Детство в Сибири, однако, закалило его, так, что теперь его самые сильные стороны - ночные операции и стрельба из автомата."),
	Nationality = "Estonia",
	Title = T(890000000004735, "A Sarcastic Bas... Teddy Bear"),
	Email = T(890000000004736, "Scream@aim.com"),
	snype_nick = T(890000000004737, "i-scream"),
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000004738, --[[ModItemUnitDataCompositeDef Jazz_Vilde Text Offline ChatMessage voice:Jazz_Vilde]] "Это Леннарт Вильде. Если вам есть что предложить, говорите после сигнала.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000004739, --[[ModItemUnitDataCompositeDef Jazz_Vilde Text GreetingAndOffer ChatMessage voice:Jazz_Vilde]] "Леннарт на связи, привет...") }) },
	ConversationRestart = { PlaceObj('ChatMessage', { 'Text', T(890000000004740, --[[ModItemUnitDataCompositeDef Jazz_Vilde Text ConversationRestart ChatMessage voice:Jazz_Vilde]] "Я повторю...") }) },
	IdleLine = { PlaceObj('ChatMessage', { 'Text', T(890000000004741, --[[ModItemUnitDataCompositeDef Jazz_Vilde Text IdleLine ChatMessage voice:Jazz_Vilde]] "Ночная операция... Она пошла бы мне на пользу.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000004742, --[[ModItemUnitDataCompositeDef Jazz_Vilde Text PartingWords ChatMessage voice:Jazz_Vilde]] "Отлично, я поспешу.") }) },
	RehireIntro = { PlaceObj('ChatMessage', { 'Text', T(890000000004743, --[[ModItemUnitDataCompositeDef Jazz_Vilde Text RehireIntro ChatMessage voice:Jazz_Vilde]] "Я был бы не против продлить контракт... Есть работа?") }) },
	RehireOutro = { PlaceObj('ChatMessage', { 'Text', T(890000000004744, --[[ModItemUnitDataCompositeDef Jazz_Vilde Text RehireOutro ChatMessage voice:Jazz_Vilde]] "Отлично. Мы договорились.") }) },
	MedicalDeposit = "small",
	StartingSalary = 1800,
	SalaryIncrease = 150,
	SalaryLv1 = 700,
	SalaryMaxLv = 4500,
	StartingLevel = 4,
	CustomEquipGear = function (self, items)
	self:TryEquip(items, "Handheld A", "Firearm")
	self:TryEquip(items, "Handheld B", "Firearm")
	end,
	MaxHitPoints = 80,
	StartingPerks = {
	"Jazz_Perk_Vilde",
	"AutoWeapons",
	"NightOps",
	"LeadFromTheFront",
	},
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "Vilde" }) },
	Equipment = { "Loot_JAZZ_Vilde" },
	Tier = "Veteran",
	Specialization = "Autoriflemen",
	pollyvoice = "Matthew",
	gender = "Male",
	VoiceResponseId = "Jazz_Vilde",
	FallbackMissingVR = "Ice",
	DaysUntilOnline = 0,
}
