UndefineClass('JAZZ_AME_26')
DefineClass.JAZZ_AME_26 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 78,
	Agility = 64,
	Dexterity = 64,
	Strength = 60,
	Wisdom = 50,
	Will = 28,
	Leadership = 8,
	Marksmanship = 54,
	Mechanical = 0,
	Explosives = 0,
	Medical = 5,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_26.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_26_Big.png",
	IsMercenary = true,
	Name = T(890000000005350, "Andile Nkosi") --[[ModItemUnitDataCompositeDef JAZZ_AME_26 Name]],
	Nick = T(890000000005351, "Andile") --[[ModItemUnitDataCompositeDef JAZZ_AME_26 Nick]],
	AllCapsNick = T(890000000005352, "ANDILE") --[[ModItemUnitDataCompositeDef JAZZ_AME_26 AllCapsNick]],
	Bio = T(890000000005353, "Андиле Нкоси охранял конвои в Южной Африке и научился стрелять очередями так, чтобы охраняемый груз не превращался в решето раньше времени. Спокоен, немногословен и не любит, когда новички трогают его оружие «просто посмотреть».") --[[ModItemUnitDataCompositeDef JAZZ_AME_26 Bio]],
	Nationality = "SouthAfrica",
	HireStatus = "NotMet",
	AMECategory = "Fighters",
	AMERole = "Autorifleman",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005354, "Дозвонился. Слушаю.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005355, "Ищу работу. Что предлагаете?") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005356, "До связи.") }) },
	MedicalDeposit = "none",
	StartingSalary = 87,
	StartingLevel = 1,
	StartingPerks = {
	"AutoWeapons",
	},
	Specialization = "Autoriflemen",
	MaxHitPoints = 78,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_26" }) },
	Equipment = { "Loot_JAZZ_AME_26" },
	gender = "Male",
	VoiceResponseId = "IMP_male_01",
	FallbackMissingVR = "IMP_male_01",
	DaysUntilOnline = 0,
}
