UndefineClass('Jazz_Shank')
DefineClass.Jazz_Shank = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "MERC",
	Health = 35,
	Agility = 35,
	Dexterity = 40,
	Strength = 30,
	Wisdom = 80,
	Will = 35,
	Leadership = 10,
	Marksmanship = 40,
	Mechanical = 10,
	Explosives = 20,
	Medical = 10,
	Portrait = "Mod/Dv3mFVN/MercPortraits/Shank.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/Shank_Big.png",
	IsMercenary = true,
	Name = T(890000000004651, "[WIP] Брием «Шенк» Друз"),
	Nick = T(890000000004652, "Шенк"),
	AllCapsNick = T(890000000004653, "ШЕНК"),
	Bio = T(890000000004654, "work in progress"),
	Nationality = "USA",
	Title = T(890000000004655, "Манчкин"),
	Email = T(890000000004656, "Shank@merc.com"),
	snype_nick = T(890000000004657, "shank"),
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000004658, --[[ModItemUnitDataCompositeDef Jazz_Shank Text Offline ChatMessage voice:Jazz_Shank]] "Shank offline.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000004659, --[[ModItemUnitDataCompositeDef Jazz_Shank Text GreetingAndOffer ChatMessage voice:Jazz_Shank]] "Shank here.") }) },
	ConversationRestart = { PlaceObj('ChatMessage', { 'Text', T(890000000004660, --[[ModItemUnitDataCompositeDef Jazz_Shank Text ConversationRestart ChatMessage voice:Jazz_Shank]] "Continue.") }) },
	IdleLine = { PlaceObj('ChatMessage', { 'Text', T(890000000004661, --[[ModItemUnitDataCompositeDef Jazz_Shank Text IdleLine ChatMessage voice:Jazz_Shank]] "Waiting.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000004662, --[[ModItemUnitDataCompositeDef Jazz_Shank Text PartingWords ChatMessage voice:Jazz_Shank]] "Hired.") }) },
	RehireIntro = { PlaceObj('ChatMessage', { 'Text', T(890000000004663, --[[ModItemUnitDataCompositeDef Jazz_Shank Text RehireIntro ChatMessage voice:Jazz_Shank]] "Contract ending?") }) },
	RehireOutro = { PlaceObj('ChatMessage', { 'Text', T(890000000004664, --[[ModItemUnitDataCompositeDef Jazz_Shank Text RehireOutro ChatMessage voice:Jazz_Shank]] "Staying.") }) },
	MedicalDeposit = "none",
	StartingSalary = 50,
	SalaryIncrease = 150,
	SalaryLv1 = 20,
	SalaryMaxLv = 400,
	StartingLevel = 1,
	CustomEquipGear = function (self, items)
	self:TryEquip(items, "Handheld A", "Firearm")
	self:TryEquip(items, "Handheld B", "Firearm")
	end,
	MaxHitPoints = 35,
	StartingPerks = {
	"Jazz_Perk_Shank",
	"Optimist",
	"Throwing",
	"MeleeTraining",
	},
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "Shank" }) },
	Equipment = { "Loot_JAZZ_Shank" },
	Tier = "Regular",
	Specialization = "Melee",
	pollyvoice = "Matthew",
	gender = "Male",
	VoiceResponseId = "Jazz_Shank",
	FallbackMissingVR = "Ice",
	DaysUntilOnline = 0,
}
