UndefineClass('JAZZ_AME_03')
DefineClass.JAZZ_AME_03 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 88,
	Agility = 58,
	Dexterity = 58,
	Strength = 62,
	Wisdom = 72,
	Will = 32,
	Leadership = 10,
	Marksmanship = 43,
	Mechanical = 0,
	Explosives = 0,
	Medical = 10,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_03.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_03_Big.png",
	IsMercenary = true,
	Name = T(890000000005120, "Ibrahim Touré") --[[ModItemUnitDataCompositeDef JAZZ_AME_03 Name]],
	Nick = T(890000000005121, "Ibrahim") --[[ModItemUnitDataCompositeDef JAZZ_AME_03 Nick]],
	AllCapsNick = T(890000000005122, "IBRAHIM") --[[ModItemUnitDataCompositeDef JAZZ_AME_03 AllCapsNick]],
	Bio = T(890000000005123, "A worn police badge shares Ibrahim Touré's pocket with a spotless handkerchief folded for the next split lip. Both survived a Malian street post where tempers caused more trouble than weapons. Ibrahim can turn a shouting match down by speaking softly, though a distant target gives him fewer clues than an angry face. When panic spreads through a crowd, he looks for the person everyone else has overlooked.") --[[ModItemUnitDataCompositeDef JAZZ_AME_03 Bio]],
	Nationality = "Mali",
	HireStatus = "NotMet",
	AMECategory = "Irregulars",
	AMERole = "Rifle",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005124, "You're through. I'm listening.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005125, "I'm looking for work. What do you have?") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005126, "All right. Speak soon.") }) },
	MedicalDeposit = "none",
	StartingSalary = 21,
	StartingLevel = 1,
	StartingPerks = {
	"Negotiator",
	},
	Specialization = "AllRounder",
	MaxHitPoints = 88,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_03" }) },
	Equipment = { "Loot_JAZZ_AME_03" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Low",
	FallbackMissingVR = "LegionRaider",
	DaysUntilOnline = 0,
}
