UndefineClass('JAZZ_AME_52')
DefineClass.JAZZ_AME_52 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 68,
	Agility = 48,
	Dexterity = 50,
	Strength = 52,
	Wisdom = 85,
	Will = 32,
	Leadership = 68,
	Marksmanship = 35,
	Mechanical = 50,
	Explosives = 28,
	Medical = 35,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_52.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_52_Big.png",
	IsMercenary = true,
	Name = T(890000000005610, "Captain Amara Koné") --[[ModItemUnitDataCompositeDef JAZZ_AME_52 Name]],
	Nick = T(890000000005611, "Amara") --[[ModItemUnitDataCompositeDef JAZZ_AME_52 Nick]],
	AllCapsNick = T(890000000005612, "AMARA") --[[ModItemUnitDataCompositeDef JAZZ_AME_52 AllCapsNick]],
	Bio = T(890000000005613, "A battered kettle goes on before Captain Amara Koné's dawn lessons, and its whistle closes the session. Malian service taught her to turn nervous soldiers into people who understood why a drill mattered. Amara rejects parade-ground drama, giving an error explanation rather than humiliation. Her own body no longer demonstrates every movement gracefully, yet the habits she plants keep working when fear makes clever advice disappear.") --[[ModItemUnitDataCompositeDef JAZZ_AME_52 Bio]],
	Nationality = "Mali",
	HireStatus = "NotMet",
	AMECategory = "Specialists",
	AMERole = "Instructor",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005614, "I'm available. We can discuss a contract.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005615, "Go ahead. Tell me what the job needs.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005616, "Understood. I will wait for your terms.") }) },
	MedicalDeposit = "none",
	StartingSalary = 264,
	StartingLevel = 1,
	StartingPerks = {
	"Teacher",
	},
	Specialization = "Leader",
	MaxHitPoints = 68,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_52" }) },
	Equipment = { "Loot_JAZZ_AME_52" },
	gender = "Female",
	VoiceResponseId = "Jazz_AME_Female",
	FallbackMissingVR = "AnneLeMitrailleur",
	DaysUntilOnline = 0,
}
