UndefineClass('Jazz_Carlos')
DefineClass.Jazz_Carlos = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AIM",
	Health = 70,
	Agility = 91,
	Dexterity = 61,
	Strength = 65,
	Wisdom = 55,
	Will = 40,
	Leadership = 30,
	Marksmanship = 67,
	Mechanical = 20,
	Explosives = 25,
	Medical = 20,
	Portrait = "Mod/Dv3mFVN/MercPortraits/Carlos.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/Carlos_Big.png",
	IsMercenary = true,
	Name = T(890000000006216, "Карлос Дасуза"),
	Nick = T(890000000006217, "Карлос"),
	AllCapsNick = T(890000000004621, "КАРЛОС"),
	Bio = T(890000000004622, "Dexterity 61, Marksmanship 67, Agility 91. Пессимист, местный повстанец. Уважает Мигеля, Иру и Дмитрия; терпеть не может Игги."),
	Nationality = "Arulco",
	Title = T(890000000004623, "Пессимист"),
	Email = T(890000000004624, "Carlos@arulco.reb"),
	snype_nick = T(890000000004625, "carlos"),
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000004626, --[[ModItemUnitDataCompositeDef Jazz_Carlos Text Offline ChatMessage voice:Jazz_Carlos]] "Карлос... зачем звонить? Всё равно плохо кончится.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000004627, --[[ModItemUnitDataCompositeDef Jazz_Carlos Text GreetingAndOffer ChatMessage voice:Jazz_Carlos]] "Карлос слушает. Плохие новости?") }) },
	ConversationRestart = { PlaceObj('ChatMessage', { 'Text', T(890000000004628, --[[ModItemUnitDataCompositeDef Jazz_Carlos Text ConversationRestart ChatMessage voice:Jazz_Carlos]] "Связь прервалась. Вернёмся к делу.") }) },
	IdleLine = { PlaceObj('ChatMessage', { 'Text', T(890000000004629, --[[ModItemUnitDataCompositeDef Jazz_Carlos Text IdleLine ChatMessage voice:Jazz_Carlos]] "Как обычно, всё плохо.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000004630, --[[ModItemUnitDataCompositeDef Jazz_Carlos Text PartingWords ChatMessage voice:Jazz_Carlos]] "Ладно. Иду. Скорее всего, зря.") }) },
	RehireIntro = { PlaceObj('ChatMessage', { 'Text', T(890000000004631, --[[ModItemUnitDataCompositeDef Jazz_Carlos Text RehireIntro ChatMessage voice:Jazz_Carlos]] "Контракт заканчивается. Продлеваем?") }) },
	RehireOutro = { PlaceObj('ChatMessage', { 'Text', T(890000000004632, --[[ModItemUnitDataCompositeDef Jazz_Carlos Text RehireOutro ChatMessage voice:Jazz_Carlos]] "Остаюсь. Хуже уже не будет.") }) },
	MedicalDeposit = "small",
	StartingSalary = 450,
	SalaryIncrease = 150,
	SalaryLv1 = 200,
	SalaryMaxLv = 1500,
	StartingLevel = 3,
	CustomEquipGear = function (self, items)
	self:TryEquip(items, "Handheld A", "Firearm")
	self:TryEquip(items, "Handheld B", "Firearm")
	end,
	MaxHitPoints = 70,
	Dislikes = {
		"Jazz_Iggy",
	},
	StartingPerks = {
	"Jazz_Perk_Carlos",
	"Pessimist",
	"Stealthy",
	"Throwing",
	},
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "Carlos" }) },
	Equipment = { "Loot_JAZZ_Carlos" },
	Tier = "Regular",
	Specialization = "Stealth",
	pollyvoice = "Matthew",
	gender = "Male",
	VoiceResponseId = "Jazz_Carlos",
	FallbackMissingVR = "Ice",
	DaysUntilOnline = 0,
}
