UndefineClass('JAZZ_AME_29')
DefineClass.JAZZ_AME_29 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 78,
	Agility = 62,
	Dexterity = 64,
	Strength = 66,
	Wisdom = 50,
	Will = 24,
	Leadership = 0,
	Marksmanship = 50,
	Mechanical = 5,
	Explosives = 12,
	Medical = 0,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_29.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_29_Big.png",
	IsMercenary = true,
	Name = T(890000000005380, "Kwesi Boateng") --[[ModItemUnitDataCompositeDef JAZZ_AME_29 Name]],
	Nick = T(890000000005381, "Kwesi") --[[ModItemUnitDataCompositeDef JAZZ_AME_29 Nick]],
	AllCapsNick = T(890000000005382, "KWESI") --[[ModItemUnitDataCompositeDef JAZZ_AME_29 AllCapsNick]],
	Bio = T(890000000005383, "Bottle caps fill Kwesi Boateng's old tobacco tin, shaken before work to hear whether his hand is steady. The habit began behind a Ghanaian warehouse, where he aimed empty bottles at a chalk circle after every shift. Heavier objects with shorter fuses eventually replaced the glass. Kwesi commits quickly but dislikes the seconds after impact, when the echo seems to search for whoever caused it.") --[[ModItemUnitDataCompositeDef JAZZ_AME_29 Bio]],
	Nationality = "Ghana",
	HireStatus = "NotMet",
	AMECategory = "Fighters",
	AMERole = "Grenadier",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005384, "On the line.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005385, "I'm listening. Tell me about the job.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005386, "Understood. I'll be here.") }) },
	MedicalDeposit = "none",
	StartingSalary = 98,
	StartingLevel = 1,
	StartingPerks = {
	"Throwing",
	"HeavyWeaponsTraining",
	},
	Specialization = "HeavyWeapons",
	MaxHitPoints = 78,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_29" }) },
	Equipment = { "Loot_JAZZ_AME_29" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Low",
	FallbackMissingVR = "LegionRaider",
	DaysUntilOnline = 0,
}
