UndefineClass('JAZZ_AME_54')
DefineClass.JAZZ_AME_54 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 72,
	Agility = 46,
	Dexterity = 48,
	Strength = 58,
	Wisdom = 88,
	Will = 34,
	Leadership = 70,
	Marksmanship = 32,
	Mechanical = 55,
	Explosives = 30,
	Medical = 40,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_54.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_54_Big.png",
	IsMercenary = true,
	Name = T(890000000005630, "Maj. Théodore Ngalula") --[[ModItemUnitDataCompositeDef JAZZ_AME_54 Name]],
	Nick = T(890000000005631, "Maj.") --[[ModItemUnitDataCompositeDef JAZZ_AME_54 Nick]],
	AllCapsNick = T(890000000005632, "MAJ.") --[[ModItemUnitDataCompositeDef JAZZ_AME_54 AllCapsNick]],
	Bio = T(890000000005633, "Майор Теодор Нгалула помнит, как строить людей так, чтобы они не разваливались в первую же неделю. Мудрость и отвёртка у него рядом с привычкой объяснять до тех пор, пока не поймут. В Гранд-Шьен его ещё помнят по званию — и по тому, что скидок на работу он не любит.") --[[ModItemUnitDataCompositeDef JAZZ_AME_54 Bio]],
	Nationality = "GrandChien",
	HireStatus = "NotMet",
	AMECategory = "Specialists",
	AMERole = "Instructor",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005634, "На связи. Готов обсуждать контракт.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005635, "Слушаю. Расскажите о задаче.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005636, "До связи.") }) },
	MedicalDeposit = "none",
	StartingSalary = 1300,
	StartingLevel = 1,
	StartingPerks = {
	"Teacher",
	},
	Specialization = "Leader",
	MaxHitPoints = 72,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_54" }) },
	Equipment = { "Loot_JAZZ_AME_54" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Hard",
	FallbackMissingVR = "ArmySoldier",
	DaysUntilOnline = 0,
}
