UndefineClass('JAZZ_AME_48')
DefineClass.JAZZ_AME_48 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 82,
	Agility = 70,
	Dexterity = 70,
	Strength = 64,
	Wisdom = 48,
	Will = 52,
	Leadership = 48,
	Marksmanship = 60,
	Mechanical = 0,
	Explosives = 10,
	Medical = 8,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_48.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_48_Big.png",
	IsMercenary = true,
	Name = T(890000000005570, "Patrick Omondi") --[[ModItemUnitDataCompositeDef JAZZ_AME_48 Name]],
	Nick = T(890000000005571, "Patrick") --[[ModItemUnitDataCompositeDef JAZZ_AME_48 Nick]],
	AllCapsNick = T(890000000005572, "PATRICK") --[[ModItemUnitDataCompositeDef JAZZ_AME_48 AllCapsNick]],
	Bio = T(890000000005573, "Black cloth covers Patrick Omondi's luminous watch and rises only beneath a cupped hand. Years on Kenyan night posts made footsteps as distinct to him as daytime faces. Patrick speaks softly after sunset, drawing tired people closer instead of competing with the dark. In daylight he is merely composed and competent; at night, patience and quiet authority seem to arrive at the same point.") --[[ModItemUnitDataCompositeDef JAZZ_AME_48 Bio]],
	Nationality = "Kenya",
	HireStatus = "NotMet",
	AMECategory = "Hardened",
	AMERole = "Rifle",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005574, "I'm here. Talk.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005575, "If there's work, I'm listening.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005576, "Send the terms.") }) },
	MedicalDeposit = "none",
	StartingSalary = 119,
	StartingLevel = 1,
	StartingPerks = {
	"NightOps",
	},
	Specialization = "Marksmen",
	MaxHitPoints = 82,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_48" }) },
	Equipment = { "Loot_JAZZ_AME_48" },
	gender = "Male",
	VoiceResponseId = "IMP_male_01",
	FallbackMissingVR = "IMP_male_01",
	DaysUntilOnline = 0,
}
