UndefineClass('JAZZ_AME_41')
DefineClass.JAZZ_AME_41 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 94,
	Agility = 62,
	Dexterity = 60,
	Strength = 90,
	Wisdom = 36,
	Will = 58,
	Leadership = 8,
	Marksmanship = 50,
	Mechanical = 0,
	Explosives = 8,
	Medical = 5,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_41.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_41_Big.png",
	IsMercenary = true,
	Name = T(890000000005500, "Sipho Khumalo") --[[ModItemUnitDataCompositeDef JAZZ_AME_41 Name]],
	Nick = T(890000000005501, "Anvil") --[[ModItemUnitDataCompositeDef JAZZ_AME_41 Nick]],
	AllCapsNick = T(890000000005502, "ANVIL") --[[ModItemUnitDataCompositeDef JAZZ_AME_41 AllCapsNick]],
	Bio = T(890000000005503, "Сифо Кхумало, «Наковальня», тащит тяжесть так, будто мир обязан подождать. Тяжёлый ствол и очереди делают своё дело — и меткость от этого страдает, он знает. Не спорит: его работа — давить сектор, а не выигрывать тир.") --[[ModItemUnitDataCompositeDef JAZZ_AME_41 Bio]],
	Nationality = "SouthAfrica",
	HireStatus = "NotMet",
	AMECategory = "Hardened",
	AMERole = "Machinegunner",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005504, "Я на линии. Говорите.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005505, "Работа есть — слушаю.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005506, "Контракт принят.") }) },
	MedicalDeposit = "none",
	StartingSalary = 520,
	StartingLevel = 1,
	StartingPerks = {
	"HeavyWeaponsTraining",
	"AutoWeapons",
	},
	Specialization = "HeavyWeapons",
	MaxHitPoints = 94,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_41" }) },
	Equipment = { "Loot_JAZZ_AME_41" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Hard",
	FallbackMissingVR = "ArmySoldier",
	DaysUntilOnline = 0,
}
