UndefineClass('JAZZ_AME_23')
DefineClass.JAZZ_AME_23 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 88,
	Agility = 58,
	Dexterity = 56,
	Strength = 78,
	Wisdom = 46,
	Will = 32,
	Leadership = 0,
	Marksmanship = 48,
	Mechanical = 0,
	Explosives = 0,
	Medical = 0,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_23.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_23_Big.png",
	IsMercenary = true,
	Name = T(890000000005320, "Chukwuemeka Obi") --[[ModItemUnitDataCompositeDef JAZZ_AME_23 Name]],
	Nick = T(890000000005321, "Emeka") --[[ModItemUnitDataCompositeDef JAZZ_AME_23 Nick]],
	AllCapsNick = T(890000000005322, "EMEKA") --[[ModItemUnitDataCompositeDef JAZZ_AME_23 AllCapsNick]],
	Bio = T(890000000005323, "Чуквуэмека Оби сидел на пулемётной точке нигерийского блокпоста, пока блокпост не стёрли с карты. Крепкий, тяжёлый, бьёт по земле увереннее, чем по мишеням — и сам над этим иногда шутит. Закрыть сектор огнём для него привычнее, чем выигрывать конкурс стрелков.") --[[ModItemUnitDataCompositeDef JAZZ_AME_23 Bio]],
	Nationality = "Nigeria",
	HireStatus = "NotMet",
	AMECategory = "Fighters",
	AMERole = "Machinegunner",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005324, "Дозвонился. Слушаю.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005325, "Ищу работу. Что предлагаете?") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005326, "До связи.") }) },
	MedicalDeposit = "none",
	StartingSalary = 260,
	StartingLevel = 1,
	StartingPerks = {
	"HeavyWeaponsTraining",
	"AutoWeapons",
	},
	Specialization = "HeavyWeapons",
	MaxHitPoints = 88,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_23" }) },
	Equipment = { "Loot_JAZZ_AME_23" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Low",
	FallbackMissingVR = "LegionRaider",
	DaysUntilOnline = 0,
}
