UndefineClass('JAZZ_AME_31')
DefineClass.JAZZ_AME_31 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 80,
	Agility = 64,
	Dexterity = 64,
	Strength = 62,
	Wisdom = 48,
	Will = 30,
	Leadership = 5,
	Marksmanship = 54,
	Mechanical = 0,
	Explosives = 0,
	Medical = 5,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_31.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_31_Big.png",
	IsMercenary = true,
	Name = T(890000000005400, "Rafael dos Santos") --[[ModItemUnitDataCompositeDef JAZZ_AME_31 Name]],
	Nick = T(890000000005401, "Rafael") --[[ModItemUnitDataCompositeDef JAZZ_AME_31 Nick]],
	AllCapsNick = T(890000000005402, "RAFAEL") --[[ModItemUnitDataCompositeDef JAZZ_AME_31 AllCapsNick]],
	Bio = T(890000000005403, "A spare bootlace circles Rafael dos Santos's wrist, recalling the day a broken boot delayed an entire column. Angolan road crews rarely saw him understand a new drill before anyone else. Rather than pretend, Rafael repeated the motion until it belonged to him. Sudden changes make him rigid, but fatigue and dust do little to loosen a promise he has already made.") --[[ModItemUnitDataCompositeDef JAZZ_AME_31 Bio]],
	Nationality = "Angola",
	HireStatus = "NotMet",
	AMECategory = "Fighters",
	AMERole = "Autorifleman",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005404, "On the line.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005405, "I'm listening. Tell me about the job.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005406, "Understood. I'll be here.") }) },
	MedicalDeposit = "none",
	StartingSalary = 89,
	StartingLevel = 1,
	StartingPerks = {
	"AutoWeapons",
	},
	Specialization = "Autoriflemen",
	MaxHitPoints = 80,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_31" }) },
	Equipment = { "Loot_JAZZ_AME_31" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Low",
	FallbackMissingVR = "LegionRaider",
	DaysUntilOnline = 0,
}
