UndefineClass('Jazz_Steiger')
DefineClass.Jazz_Steiger = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AIM",
	Health = 80,
	Agility = 75,
	Dexterity = 75,
	Strength = 69,
	Wisdom = 90,
	Will = 70,
	Leadership = 69,
	Marksmanship = 94,
	Mechanical = 35,
	Explosives = 35,
	Medical = 30,
	Portrait = "Mod/Dv3mFVN/MercPortraits/Steiger.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/Steiger_Big.png",
	IsMercenary = true,
	Name = T(890000000004763, "Рудольф Штайгер"),
	Nick = T(890000000004764, "Штайгер"),
	AllCapsNick = T(890000000004765, "ШТАЙГЕР"),
	Bio = T(890000000004766, "Wildfire. Статы 75–85, Сила 69, Мудрость 90, Лидерство 69, Меткость 94. Плохо переносит жару. Любит Хеннинга, Лору и Гранти; недолюбливает Корда и Булла. Очень дорогой специалист."),
	Nationality = "Germany",
	Title = T(890000000004767, "Дорогой немец"),
	Email = T(890000000004768, "Steiger@aim.com"),
	snype_nick = T(890000000004769, "steiger"),
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000004770, --[[ModItemUnitDataCompositeDef Jazz_Steiger Text Offline ChatMessage voice:Jazz_Steiger]] "Говорит Рудольф Штайгер. Оставьте сообщение. Возможно, я перезвоню.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000004771, --[[ModItemUnitDataCompositeDef Jazz_Steiger Text GreetingAndOffer ChatMessage voice:Jazz_Steiger]] "Привет...") }) },
	ConversationRestart = { PlaceObj('ChatMessage', { 'Text', T(890000000004772, --[[ModItemUnitDataCompositeDef Jazz_Steiger Text ConversationRestart ChatMessage voice:Jazz_Steiger]] "Я сказал...") }) },
	IdleLine = { PlaceObj('ChatMessage', { 'Text', T(890000000004773, --[[ModItemUnitDataCompositeDef Jazz_Steiger Text IdleLine ChatMessage voice:Jazz_Steiger]] "Мне есть, чем заняться...") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000004774, --[[ModItemUnitDataCompositeDef Jazz_Steiger Text PartingWords ChatMessage voice:Jazz_Steiger]] "Отлично, уже еду.") }) },
	RehireIntro = { PlaceObj('ChatMessage', { 'Text', T(890000000004775, --[[ModItemUnitDataCompositeDef Jazz_Steiger Text RehireIntro ChatMessage voice:Jazz_Steiger]] "Заинтересован в продлении контракта? Я бы не отказался...") }) },
	RehireOutro = { PlaceObj('ChatMessage', { 'Text', T(890000000004776, --[[ModItemUnitDataCompositeDef Jazz_Steiger Text RehireOutro ChatMessage voice:Jazz_Steiger]] "Выпьем за долгое и взаимовыгодное сотрудничество...") }) },
	MedicalDeposit = "large",
	StartingSalary = 5500,
	SalaryIncrease = 150,
	SalaryLv1 = 2500,
	SalaryMaxLv = 11000,
	StartingLevel = 5,
	CustomEquipGear = function (self, items)
	self:TryEquip(items, "Handheld A", "Firearm")
	self:TryEquip(items, "Handheld B", "Firearm")
	end,
	MaxHitPoints = 80,
	StartingPerks = {
	"Jazz_Perk_Steiger",
	"NightOps",
	"Teacher",
	"LeadFromTheFront",
	},
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "Steiger" }) },
	Equipment = { "Loot_JAZZ_Steiger" },
	Tier = "Elite",
	Specialization = "Leader",
	pollyvoice = "Matthew",
	gender = "Male",
	VoiceResponseId = "Jazz_Steiger",
	FallbackMissingVR = "Ice",
	DaysUntilOnline = 0,
}
