UndefineClass('Jazz_lynx')
DefineClass.Jazz_lynx = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",


	object_class = "UnitData",
	Health = 81,
	Agility = 79,
	Dexterity = 86,
	Strength = 77,
	Wisdom = 82,
	Leadership = 39,
	Marksmanship = 99,
	Mechanical = 29,
	Explosives = 50,
	Medical = 34,
	Portrait = "Mod/Dv3mFVN/Images/lynxsmall.png",
	BigPortrait = "Mod/Dv3mFVN/Images/lynxbig.png",
	IsMercenary = true,
	Name = T(937969002541, --[[ModItemUnitDataCompositeDef Jazz_lynx Name]] 'Руди "Рысь" Робертс'),
	Nick = T(859608556305, --[[ModItemUnitDataCompositeDef Jazz_lynx Nick]] "Рысь"),
	AllCapsNick = T(612897757725, --[[ModItemUnitDataCompositeDef Jazz_lynx AllCapsNick]] "РЫСЬ"),
	Bio = T(563244082370, --[[ModItemUnitDataCompositeDef Jazz_lynx Bio]] "Once a Major in the Red Army, Ivan took his combat skills to the free market after the collapse of the Soviet Union. Although he still struggles to put anything more than the simplest of phrases into English, his enormous martial talents have only grown during his membership with A.I.M. His feats are so legendary, Hollywood tried to make a movie about him, but since he insisted on starring in it and only using live ammunition the project was canceled."),
	Nationality = "USA",
	Title = T(789609298271, --[[ModItemUnitDataCompositeDef Jazz_lynx Title]] "Lynx-Eyed from USA"),
	Email = T(631563903596, --[[ModItemUnitDataCompositeDef Jazz_lynx Email]] "Lynx@aim.com"),
	snype_nick = T(961825378163, --[[ModItemUnitDataCompositeDef Jazz_lynx snype_nick]] "рысь"),
	Refusals = {},
	Mitigations = {},
	ExtraPartingWords = {},
	Offline = {},
	GreetingAndOffer = {},
	ConversationRestart = {},
	IdleLine = {},
	PartingWords = {},
	RehireIntro = {},
	RehireOutro = {},
	StartingSalary = 2650,
	SalaryIncrease = 200,
	SalaryLv1 = 1400,
	SalaryMaxLv = 6200,
	LegacyNotes = 'JA1\n\n"A new member and a onetime decorated Major in the Red Army, Ivan Dolvich has, like his country, switched from killing for Lenin to dying for Lincolns. However, unlike his homeland, Ivan actually appears to be good at it." \n\nJA2\n\n"Ivan, a former highly decorated Red Army Major, joined the organization over three years ago on a freelance assignment. Despite serious difficulties communicating in English, he took the mercenary world by storm, breaking all kill-rate records and tallying up the kind of stats that perhaps only he himself is capable of breaking. Ivan himself says it best, \'gun, all gun, like finger on hand.\' In order to improve his relationship with commanders, Ivan has enrolled in an "English as a second language" course."\n\nSkills - Auto Weapons; Heavy Weapons',
	StartingLevel = 4,
	MaxHitPoints = 94,
	StartingPerks = {
		"AutoWeapons",
		"NightOps",
		"MrFixit",
		"Jazz_Lynx_Perk",
		"Pessimist",
		"Deadeye",
	},
	AppearancesList = {
		PlaceObj('AppearanceWeight', {
			'Preset', "Lynx",
		}),
	},
	Equipment = {
		"Loot_JAZZ_Lynx",
	},
	Tier = "Elite",
	Specialization = "Autoriflemen",
	pollyvoice = "Russell",
	gender = "Male",
}

