UndefineClass('JAZZ_AME_24')
DefineClass.JAZZ_AME_24 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 80,
	Agility = 66,
	Dexterity = 66,
	Strength = 62,
	Wisdom = 54,
	Will = 26,
	Leadership = 5,
	Marksmanship = 56,
	Mechanical = 0,
	Explosives = 12,
	Medical = 5,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_24.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_24_Big.png",
	IsMercenary = true,
	Name = T(890000000005330, "Michel Kabeya") --[[ModItemUnitDataCompositeDef JAZZ_AME_24 Name]],
	Nick = T(890000000005331, "Michel") --[[ModItemUnitDataCompositeDef JAZZ_AME_24 Nick]],
	AllCapsNick = T(890000000005332, "MICHEL") --[[ModItemUnitDataCompositeDef JAZZ_AME_24 AllCapsNick]],
	Bio = T(890000000005333, "Michel Kabeya once unloaded riverboats in Congo, betting his lunch on whether a dented can would land inside a distant crate. The game eventually became a practical occupation involving objects no one wanted thrown back. He is loud over drinks and utterly silent before a toss, rubbing a copper pull ring threaded onto his belt. Michel trusts his arm, but never lingers to admire the place where its delivery comes down.") --[[ModItemUnitDataCompositeDef JAZZ_AME_24 Bio]],
	Nationality = "Congo",
	HireStatus = "NotMet",
	AMECategory = "Fighters",
	AMERole = "Grenadier",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005334, "On the line.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005335, "I'm listening. Tell me about the job.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005336, "Understood. I'll be here.") }) },
	MedicalDeposit = "none",
	StartingSalary = 95,
	StartingLevel = 1,
	StartingPerks = {
	"Throwing",
	},
	Specialization = "HeavyWeapons",
	MaxHitPoints = 80,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_24" }) },
	Equipment = { "Loot_JAZZ_AME_24" },
	gender = "Male",
	VoiceResponseId = "IMP_male_01",
	FallbackMissingVR = "IMP_male_01",
	DaysUntilOnline = 0,
}
