UndefineClass('JAZZ_AME_43')
DefineClass.JAZZ_AME_43 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 78,
	Agility = 68,
	Dexterity = 70,
	Strength = 70,
	Wisdom = 44,
	Will = 48,
	Leadership = 5,
	Marksmanship = 58,
	Mechanical = 5,
	Explosives = 14,
	Medical = 5,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_43.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_43_Big.png",
	IsMercenary = true,
	Name = T(890000000005520, "Didier Mbemba") --[[ModItemUnitDataCompositeDef JAZZ_AME_43 Name]],
	Nick = T(890000000005521, "Smoke") --[[ModItemUnitDataCompositeDef JAZZ_AME_43 Nick]],
	AllCapsNick = T(890000000005522, "SMOKE") --[[ModItemUnitDataCompositeDef JAZZ_AME_43 AllCapsNick]],
	Bio = T(890000000005523, "Дидье Мбемба, «Дым», из Конго приходит с банками и уходит в дыму, который сам же и ставит. Не спринтер — зато сектор задымления знает наизусть. Когда тишина уже не вариант, он как раз на месте.") --[[ModItemUnitDataCompositeDef JAZZ_AME_43 Bio]],
	Nationality = "Congo",
	HireStatus = "NotMet",
	AMECategory = "Hardened",
	AMERole = "Grenadier",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005524, "Я на линии. Говорите.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005525, "Работа есть — слушаю.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005526, "Контракт принят.") }) },
	MedicalDeposit = "none",
	StartingSalary = 500,
	StartingLevel = 1,
	StartingPerks = {
	"Throwing",
	"HeavyWeaponsTraining",
	},
	Specialization = "ExplosiveExpert",
	MaxHitPoints = 78,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_43" }) },
	Equipment = { "Loot_JAZZ_AME_43" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Hard",
	FallbackMissingVR = "ArmySoldier",
	DaysUntilOnline = 0,
}
