UndefineClass('JAZZ_AME_14')
DefineClass.JAZZ_AME_14 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 82,
	Agility = 64,
	Dexterity = 60,
	Strength = 56,
	Wisdom = 62,
	Will = 27,
	Leadership = 0,
	Marksmanship = 45,
	Mechanical = 0,
	Explosives = 0,
	Medical = 0,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_14.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_14_Big.png",
	IsMercenary = true,
	Name = T(890000000005230, "Lucien Mbarga") --[[ModItemUnitDataCompositeDef JAZZ_AME_14 Name]],
	Nick = T(890000000005231, "Lucien") --[[ModItemUnitDataCompositeDef JAZZ_AME_14 Nick]],
	AllCapsNick = T(890000000005232, "LUCIEN") --[[ModItemUnitDataCompositeDef JAZZ_AME_14 AllCapsNick]],
	Bio = T(890000000005233, "An expired licence lies absurdly neat inside Lucien Mbarga's knife sheath after many wet seasons. It survived the day Grand Chien rangers confiscated his poaching gun and promised a cell next time. Lucien performs no regret for company, preferring to leave before questions grow specific. Empty-handed at distance, he falls back on the craft nobody managed to seize: moving without announcing himself.") --[[ModItemUnitDataCompositeDef JAZZ_AME_14 Bio]],
	Nationality = "GrandChien",
	HireStatus = "NotMet",
	AMECategory = "Irregulars",
	AMERole = "Rifle",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005234, "You're through. I'm listening.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005235, "I'm looking for work. What do you have?") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005236, "All right. Speak soon.") }) },
	MedicalDeposit = "none",
	StartingSalary = 41,
	StartingLevel = 1,
		StartingPerks = {
	"Scoundrel",
	},,
	Specialization = "AllRounder",
	MaxHitPoints = 82,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_14" }) },
	Equipment = { "Loot_JAZZ_AME_14" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Hard",
	FallbackMissingVR = "ArmySoldier",
	DaysUntilOnline = 0,
}
