UndefineClass('JAZZ_AME_48')
DefineClass.JAZZ_AME_48 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 82,
	Agility = 70,
	Dexterity = 70,
	Strength = 64,
	Wisdom = 48,
	Will = 52,
	Leadership = 48,
	Marksmanship = 60,
	Mechanical = 0,
	Explosives = 10,
	Medical = 8,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_48.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_48_Big.png",
	IsMercenary = true,
	Name = T(890000000005570, "Patrick Omondi") --[[ModItemUnitDataCompositeDef JAZZ_AME_48 Name]],
	Nick = T(890000000005571, "Patrick") --[[ModItemUnitDataCompositeDef JAZZ_AME_48 Nick]],
	AllCapsNick = T(890000000005572, "PATRICK") --[[ModItemUnitDataCompositeDef JAZZ_AME_48 AllCapsNick]],
	Bio = T(890000000005573, "Патрик Омонди — ночной стрелок из Кении со спокойным голосом, к которому прислушиваются даже уставшие. Лучше видит в темноте и лучше ждёт. После заката говорит шёпотом так, что всё равно слушаются.") --[[ModItemUnitDataCompositeDef JAZZ_AME_48 Bio]],
	Nationality = "Kenya",
	HireStatus = "NotMet",
	AMECategory = "Hardened",
	AMERole = "Rifle",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005574, "Я на линии. Говорите.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005575, "Работа есть — слушаю.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005576, "Контракт принят.") }) },
	MedicalDeposit = "none",
	StartingSalary = 119,
	StartingLevel = 1,
	StartingPerks = {
	"NightOps",
	},
	Specialization = "Marksmen",
	MaxHitPoints = 82,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_48" }) },
	Equipment = { "Loot_JAZZ_AME_48" },
	gender = "Male",
	VoiceResponseId = "IMP_male_01",
	FallbackMissingVR = "IMP_male_01",
	DaysUntilOnline = 0,
}
