UndefineClass('JAZZ_AME_34')
DefineClass.JAZZ_AME_34 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 90,
	Agility = 56,
	Dexterity = 54,
	Strength = 80,
	Wisdom = 44,
	Will = 34,
	Leadership = 5,
	Marksmanship = 48,
	Mechanical = 0,
	Explosives = 0,
	Medical = 0,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_34.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_34_Big.png",
	IsMercenary = true,
	Name = T(890000000005430, "Emeka Nwosu") --[[ModItemUnitDataCompositeDef JAZZ_AME_34 Name]],
	Nick = T(890000000005431, "Emeka") --[[ModItemUnitDataCompositeDef JAZZ_AME_34 Nick]],
	AllCapsNick = T(890000000005432, "EMEKA") --[[ModItemUnitDataCompositeDef JAZZ_AME_34 AllCapsNick]],
	Bio = T(890000000005433, "An empty ammunition box serves as Emeka Nwosu's chair and carries the label, “Do not relocate with owner.” Nigerian quay work first revealed that he could carry a machine gun farther than anyone else. Finesse never followed, but good humour did whenever the joke concerns his immovable size. Emeka struggles with delicate choices at distance, yet weight, recoil, and stubborn ground suit him perfectly.") --[[ModItemUnitDataCompositeDef JAZZ_AME_34 Bio]],
	Nationality = "Nigeria",
	HireStatus = "NotMet",
	AMECategory = "Fighters",
	AMERole = "Machinegunner",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005434, "On the line.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005435, "I'm listening. Tell me about the job.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005436, "Understood. I'll be here.") }) },
	MedicalDeposit = "none",
	StartingSalary = 107,
	StartingLevel = 1,
	StartingPerks = {
	"HeavyWeaponsTraining",
	"AutoWeapons",
	},
	Specialization = "HeavyWeapons",
	MaxHitPoints = 90,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_34" }) },
	Equipment = { "Loot_JAZZ_AME_34" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Hard",
	FallbackMissingVR = "ArmySoldier",
	DaysUntilOnline = 0,
}
