UndefineClass('JAZZ_AME_47')
DefineClass.JAZZ_AME_47 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 80,
	Agility = 70,
	Dexterity = 70,
	Strength = 66,
	Wisdom = 46,
	Will = 50,
	Leadership = 8,
	Marksmanship = 60,
	Mechanical = 5,
	Explosives = 14,
	Medical = 5,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_47.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_47_Big.png",
	IsMercenary = true,
	Name = T(890000000005560, "Hassan Ibrahim") --[[ModItemUnitDataCompositeDef JAZZ_AME_47 Name]],
	Nick = T(890000000005561, "Scorpion") --[[ModItemUnitDataCompositeDef JAZZ_AME_47 Nick]],
	AllCapsNick = T(890000000005562, "SCORPION") --[[ModItemUnitDataCompositeDef JAZZ_AME_47 AllCapsNick]],
	Bio = T(890000000005563, "Хассана Ибрахима в Мали зовут «Скорпион»: быстрее многих ветеранов, с ухмылкой человека, который любит, когда взрыв случается вовремя. Бросок уверенный, характер ядовитый. Кличка известнее имени — и он над этим не работает.") --[[ModItemUnitDataCompositeDef JAZZ_AME_47 Bio]],
	Nationality = "Mali",
	HireStatus = "NotMet",
	AMECategory = "Hardened",
	AMERole = "Grenadier",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005564, "Я на линии. Говорите.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005565, "Работа есть — слушаю.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005566, "Контракт принят.") }) },
	MedicalDeposit = "none",
	StartingSalary = 510,
	StartingLevel = 1,
	StartingPerks = {
	"Throwing",
	},
	Specialization = "ExplosiveExpert",
	MaxHitPoints = 80,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_47" }) },
	Equipment = { "Loot_JAZZ_AME_47" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Hard",
	FallbackMissingVR = "ArmySoldier",
	DaysUntilOnline = 0,
}
