UndefineClass('JAZZ_AME_57')
DefineClass.JAZZ_AME_57 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 70,
	Agility = 48,
	Dexterity = 52,
	Strength = 55,
	Wisdom = 60,
	Will = 26,
	Leadership = 8,
	Marksmanship = 24,
	Mechanical = 50,
	Explosives = 68,
	Medical = 8,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_57.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_57_Big.png",
	IsMercenary = true,
	Name = T(890000000005660, "Bakary Diarra") --[[ModItemUnitDataCompositeDef JAZZ_AME_57 Name]],
	Nick = T(890000000005661, "Bakary") --[[ModItemUnitDataCompositeDef JAZZ_AME_57 Nick]],
	AllCapsNick = T(890000000005662, "BAKARY") --[[ModItemUnitDataCompositeDef JAZZ_AME_57 AllCapsNick]],
	Bio = T(890000000005663, "Бакари Диарра из Мали однажды пропил пистолет на детонаторы — и не жалеет. Взрывчатку знает лучше стрельбы, и сам об этом не стесняется. Его боятся ровно настолько, насколько уважают.") --[[ModItemUnitDataCompositeDef JAZZ_AME_57 Bio]],
	Nationality = "Mali",
	HireStatus = "NotMet",
	AMECategory = "Specialists",
	AMERole = "Sapper",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005664, "На связи. Готов обсуждать контракт.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005665, "Слушаю. Расскажите о задаче.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005666, "До связи.") }) },
	MedicalDeposit = "none",
	StartingSalary = 720,
	StartingLevel = 1,
	StartingPerks = {
	"Throwing",
	},
	Specialization = "ExplosiveExpert",
	MaxHitPoints = 70,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_57" }) },
	Equipment = { "Loot_JAZZ_AME_57" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Hard",
	FallbackMissingVR = "ArmySoldier",
	DaysUntilOnline = 0,
}
