UndefineClass('JAZZ_AME_28')
DefineClass.JAZZ_AME_28 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 86,
	Agility = 56,
	Dexterity = 58,
	Strength = 74,
	Wisdom = 46,
	Will = 30,
	Leadership = 5,
	Marksmanship = 50,
	Mechanical = 0,
	Explosives = 5,
	Medical = 0,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_28.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_28_Big.png",
	IsMercenary = true,
	Name = T(890000000005370, "Pascal Ngoma") --[[ModItemUnitDataCompositeDef JAZZ_AME_28 Name]],
	Nick = T(890000000005371, "Pascal") --[[ModItemUnitDataCompositeDef JAZZ_AME_28 Nick]],
	AllCapsNick = T(890000000005372, "PASCAL") --[[ModItemUnitDataCompositeDef JAZZ_AME_28 AllCapsNick]],
	Bio = T(890000000005373, "A ridiculous folding stool appears beneath Pascal Ngoma whenever waiting stretches past an hour. Grand Chien gun posts taught him to regard running as evidence of poor planning. Pascal is stubborn, durable, and happiest when a patch of ground becomes clearly his responsibility. New directions reach him slowly, but incoming noise rarely persuades him to leave the old one.") --[[ModItemUnitDataCompositeDef JAZZ_AME_28 Bio]],
	Nationality = "GrandChien",
	HireStatus = "NotMet",
	AMECategory = "Fighters",
	AMERole = "Machinegunner",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005374, "On the line.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005375, "I'm listening. Tell me about the job.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005376, "Understood. I'll be here.") }) },
	MedicalDeposit = "none",
	StartingSalary = 104,
	StartingLevel = 1,
	StartingPerks = {
	"HeavyWeaponsTraining",
	},
	Specialization = "HeavyWeapons",
	MaxHitPoints = 86,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_28" }) },
	Equipment = { "Loot_JAZZ_AME_28" },
	gender = "Male",
	VoiceResponseId = "PierreMerc",
	FallbackMissingVR = "PierreMerc",
	DaysUntilOnline = 0,
}
