UndefineClass('Jazz_Devin')
DefineClass.Jazz_Devin = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AIM",
	Health = 73,
	Agility = 61,
	Dexterity = 88,
	Strength = 71,
	Wisdom = 72,
	Will = 45,
	Leadership = 11,
	Marksmanship = 67,
	Mechanical = 34,
	Explosives = 96,
	Medical = 5,
	Portrait = "Mod/Dv3mFVN/MercPortraits/Devin.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/Devin_Big.png",
	IsMercenary = true,
	Name = T(890000000004635, "Девин Коннелл"),
	Nick = T(890000000004636, "Девин"),
	AllCapsNick = T(890000000004637, "ДЕВИН"),
	Bio = T(890000000004638, "Рыжий. Ирландец. Торгует взрывчаткой. Что он забыл в поглощенном гражданской войной Арулько? А, ну да. Рано или поздно, Девин предложил свои услуги Организации, да так и остался на контракте. У саперов высокая текучка, ими разбрасываться нельзя."),
	Nationality = "Ireland",
	Title = T(890000000004639, "Enough Lounging Around with You Lot"),
	Email = T(890000000004640, "Devin@arulco.local"),
	snype_nick = T(890000000004641, "Irishboom"),
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000004642, --[[ModItemUnitDataCompositeDef Jazz_Devin Text Offline ChatMessage voice:Jazz_Devin]] "Девин занят. Позже.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000004643, --[[ModItemUnitDataCompositeDef Jazz_Devin Text GreetingAndOffer ChatMessage voice:Jazz_Devin]] "Коннелл слушает.") }) },
	ConversationRestart = { PlaceObj('ChatMessage', { 'Text', T(890000000004644, --[[ModItemUnitDataCompositeDef Jazz_Devin Text ConversationRestart ChatMessage voice:Jazz_Devin]] "Связь прервалась. Вернёмся к делу.") }) },
	IdleLine = { PlaceObj('ChatMessage', { 'Text', T(890000000004645, --[[ModItemUnitDataCompositeDef Jazz_Devin Text IdleLine ChatMessage voice:Jazz_Devin]] "Ну что, есть что взорвать?") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000004646, --[[ModItemUnitDataCompositeDef Jazz_Devin Text PartingWords ChatMessage voice:Jazz_Devin]] "За такую цену — идёт.") }) },
	RehireIntro = { PlaceObj('ChatMessage', { 'Text', T(890000000004647, --[[ModItemUnitDataCompositeDef Jazz_Devin Text RehireIntro ChatMessage voice:Jazz_Devin]] "Контракт заканчивается. Продлеваем?") }) },
	RehireOutro = { PlaceObj('ChatMessage', { 'Text', T(890000000004648, --[[ModItemUnitDataCompositeDef Jazz_Devin Text RehireOutro ChatMessage voice:Jazz_Devin]] "Остаюсь.") }) },
	MedicalDeposit = "small",
	StartingSalary = 2000,
	SalaryIncrease = 150,
	SalaryLv1 = 800,
	SalaryMaxLv = 5000,
	StartingLevel = 3,
	CustomEquipGear = function (self, items)
	self:TryEquip(items, "Handheld A", "Firearm")
	self:TryEquip(items, "Handheld B", "Firearm")
	end,
	MaxHitPoints = 68,
	StartingPerks = {
	"Jazz_Perk_Devin",
	"Loner",
	"BreachAndClear",
	},
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "Devin" }) },
	Equipment = { "Loot_JAZZ_Devin" },
	Tier = "Veteran",
	Specialization = "ExplosiveExpert",
	pollyvoice = "Matthew",
	gender = "Male",
	VoiceResponseId = "Jazz_Devin",
	FallbackMissingVR = "Ice",
	DaysUntilOnline = 0,
}
