UndefineClass('Jazz_Laura')
DefineClass.Jazz_Laura = {
	Dislikes = {
					"Fox",
					"Jazz_Buzz",
				},
	Likes = {
					"Jazz_Steiger",
					"Jazz_Monk",
				},
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AIM",
	Health = 78,
	Agility = 72,
	Dexterity = 85,
	Strength = 70,
	Wisdom = 87,
	Will = 51,
	Leadership = 25,
	Marksmanship = 82,
	Mechanical = 33,
	Explosives = 57,
	Medical = 74,
	Portrait = "Mod/Dv3mFVN/MercPortraits/Laura.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/Laura_Big.png",
	IsMercenary = true,
	Name = T(890000000004795, "Доктор Лора Колин"),
	Nick = T(890000000004796, "Лора"),
	AllCapsNick = T(890000000004797, "ЛОРА"),
	Bio = T(890000000004798, "Лора Колин родилась в Румынии. Ее родители-диссиденты бежали в Германию, опасаясь ареста. От них она унаследовала нелюбовь к диктаторам. Училась на медика, и попала в A.I.M. по совету Рудольфа Штайгера. Страстная наемница! Ее сильные стороны - выслеживание противника и стрельба из автоматического оружия. Ненавидит работать со Луизой Гарно."),
	Nationality = "Romania",
	Title = T(890000000004799, "Heals with One Hand, Blows Things Up with the Other"),
	Email = T(890000000004800, "Laura@aim.com"),
	snype_nick = T(890000000004801, "laura"),
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000004802, --[[ModItemUnitDataCompositeDef Jazz_Laura Text Offline ChatMessage voice:Jazz_Laura]] "Это врач Лора Колин. В неотложных случаях вы можете отправить сообщение на мой пейджер.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000004803, --[[ModItemUnitDataCompositeDef Jazz_Laura Text GreetingAndOffer ChatMessage voice:Jazz_Laura]] "Алло?") }) },
	ConversationRestart = { PlaceObj('ChatMessage', { 'Text', T(890000000004804, --[[ModItemUnitDataCompositeDef Jazz_Laura Text ConversationRestart ChatMessage voice:Jazz_Laura]] "Я повторю.") }) },
	IdleLine = { PlaceObj('ChatMessage', { 'Text', T(890000000004805, --[[ModItemUnitDataCompositeDef Jazz_Laura Text IdleLine ChatMessage voice:Jazz_Laura]] "Может быть, пока сделаем пару... растяжек, отжиманий? Другими словами, зарядку?") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000004806, --[[ModItemUnitDataCompositeDef Jazz_Laura Text PartingWords ChatMessage voice:Jazz_Laura]] "Да. Я думаю, этот контракт окажется интересным.") }) },
	RehireIntro = { PlaceObj('ChatMessage', { 'Text', T(890000000004807, --[[ModItemUnitDataCompositeDef Jazz_Laura Text RehireIntro ChatMessage voice:Jazz_Laura]] "Возможно, вы согласитесь продлить контракт?") }) },
	RehireOutro = { PlaceObj('ChatMessage', { 'Text', T(890000000004808, --[[ModItemUnitDataCompositeDef Jazz_Laura Text RehireOutro ChatMessage voice:Jazz_Laura]] "Отлично. Мы договорились.") }) },
	MedicalDeposit = "extreme",
	StartingSalary = 1750,
	SalaryIncrease = 230,
	SalaryLv1 = 600,
	SalaryMaxLv = 4200,
	StartingLevel = 5,
	CustomEquipGear = function (self, items)
	self:TryEquip(items, "Handheld A", "Firearm")
	self:TryEquip(items, "Handheld B", "Firearm")
	end,
	MaxHitPoints = 75,
	StartingPerks = {
	"Jazz_Perk_Laura",
	"Stealthy",
	"TrueGrit",
	},
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "Laura" }) },
	Equipment = { "Loot_JAZZ_Laura" },
	Tier = "Regular",
	Specialization = "Autoriflemen",
	pollyvoice = "Amy",
	gender = "Female",
	VoiceResponseId = "Jazz_Laura",
	FallbackMissingVR = "Ice",
	DaysUntilOnline = 0,
}
