UndefineClass('JAZZ_AME_22')
DefineClass.JAZZ_AME_22 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 76,
	Agility = 64,
	Dexterity = 64,
	Strength = 58,
	Wisdom = 52,
	Will = 28,
	Leadership = 5,
	Marksmanship = 54,
	Mechanical = 0,
	Explosives = 0,
	Medical = 5,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_22.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_22_Big.png",
	IsMercenary = true,
	Name = T(890000000005310, "Bastien Lafontaine") --[[ModItemUnitDataCompositeDef JAZZ_AME_22 Name]],
	Nick = T(890000000005311, "Bastien") --[[ModItemUnitDataCompositeDef JAZZ_AME_22 Nick]],
	AllCapsNick = T(890000000005312, "BASTIEN") --[[ModItemUnitDataCompositeDef JAZZ_AME_22 AllCapsNick]],
	Bio = T(890000000005313, "Бастьен Лафонтен служил милицейским автоматчиком в Гранд-Шьен и до сих пор пахнет машинным маслом и дешёвым табаком. Очереди для него важнее красоты ствола: улица становится тесной — и он уже на линии. Платят лучше участка — и этого ему достаточно.") --[[ModItemUnitDataCompositeDef JAZZ_AME_22 Bio]],
	Nationality = "GrandChien",
	HireStatus = "NotMet",
	AMECategory = "Fighters",
	AMERole = "Autorifleman",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005314, "Дозвонился. Слушаю.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005315, "Ищу работу. Что предлагаете?") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005316, "До связи.") }) },
	MedicalDeposit = "none",
	StartingSalary = 240,
	StartingLevel = 1,
	StartingPerks = {
	"AutoWeapons",
	},
	Specialization = "Autoriflemen",
	MaxHitPoints = 76,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_22" }) },
	Equipment = { "Loot_JAZZ_AME_22" },
	gender = "Male",
	VoiceResponseId = "IMP_male_01",
	FallbackMissingVR = "IMP_male_01",
	DaysUntilOnline = 0,
}
