UndefineClass('JAZZ_AME_56')
DefineClass.JAZZ_AME_56 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 52,
	Agility = 66,
	Dexterity = 60,
	Strength = 46,
	Wisdom = 55,
	Will = 30,
	Leadership = 12,
	Marksmanship = 70,
	Mechanical = 15,
	Explosives = 0,
	Medical = 8,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_56.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_56_Big.png",
	IsMercenary = true,
	Name = T(890000000005650, "Lindiwe Mokoena") --[[ModItemUnitDataCompositeDef JAZZ_AME_56 Name]],
	Nick = T(890000000005651, "Lindiwe") --[[ModItemUnitDataCompositeDef JAZZ_AME_56 Nick]],
	AllCapsNick = T(890000000005652, "LINDIWE") --[[ModItemUnitDataCompositeDef JAZZ_AME_56 AllCapsNick]],
	Bio = T(890000000005653, "Линдиве Мокоена работает ночью. Хрупкая, зоркая; темнота для неё союзник, а не чужой кошмар. Не обещает чудес и не набивает цену громкими словами. Любит, когда дело заканчивается одним тихим щелчком.") --[[ModItemUnitDataCompositeDef JAZZ_AME_56 Bio]],
	Nationality = "SouthAfrica",
	HireStatus = "NotMet",
	AMECategory = "Specialists",
	AMERole = "Sniper",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005654, "На связи. Готов обсуждать контракт.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005655, "Слушаю. Расскажите о задаче.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005656, "До связи.") }) },
	MedicalDeposit = "none",
	StartingSalary = 820,
	StartingLevel = 1,
	StartingPerks = {
	"NightOps",
	},
	Specialization = "Marksmen",
	MaxHitPoints = 52,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_56" }) },
	Equipment = { "Loot_JAZZ_AME_56" },
	gender = "Female",
	VoiceResponseId = "Jazz_AME_Female",
	FallbackMissingVR = "AnneLeMitrailleur",
	DaysUntilOnline = 0,
}
