UndefineClass('Jazz_Meat')
DefineClass.Jazz_Meat = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "MERC",
	Health = 90,
	Agility = 54,
	Dexterity = 68,
	Strength = 98,
	Wisdom = 29,
	Will = 50,
	Leadership = 10,
	Marksmanship = 55,
	Mechanical = 59,
	Explosives = 64,
	Medical = 5,
	Portrait = "Mod/Dv3mFVN/MercPortraits/Meat.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/Meat_Big.png",
	IsMercenary = true,
	Name = T(890000000006202, "Тортон «Мясо» Джонс"),
	Nick = T(890000000006203, "Мясо"),
	AllCapsNick = T(890000000006204, "МЯСО"),
	Bio = T(890000000006205, "Dexterity 68, Agility 54, Wisdom 29, Strength 98, Mechanical 59, Explosives 64. Агрессивен и туповат, но взрывчатку носит и ставит без страха. Дружит с Быком; странно запал на Тоску. Его недолюбливают почти все местные из Арулько."),
	Nationality = "USA",
	Title = T(890000000006206, "Гора"),
	Email = T(890000000006207, "Meat@merc.com"),
	snype_nick = T(890000000006208, "meat"),
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000006209, --[[ModItemUnitDataCompositeDef Jazz_Meat Text Offline ChatMessage voice:Jazz_Meat]] "Meat offline.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000006210, --[[ModItemUnitDataCompositeDef Jazz_Meat Text GreetingAndOffer ChatMessage voice:Jazz_Meat]] "Meat here.") }) },
	ConversationRestart = { PlaceObj('ChatMessage', { 'Text', T(890000000006211, --[[ModItemUnitDataCompositeDef Jazz_Meat Text ConversationRestart ChatMessage voice:Jazz_Meat]] "Continue.") }) },
	IdleLine = { PlaceObj('ChatMessage', { 'Text', T(890000000006212, --[[ModItemUnitDataCompositeDef Jazz_Meat Text IdleLine ChatMessage voice:Jazz_Meat]] "Waiting.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000006213, --[[ModItemUnitDataCompositeDef Jazz_Meat Text PartingWords ChatMessage voice:Jazz_Meat]] "Hired.") }) },
	RehireIntro = { PlaceObj('ChatMessage', { 'Text', T(890000000006214, --[[ModItemUnitDataCompositeDef Jazz_Meat Text RehireIntro ChatMessage voice:Jazz_Meat]] "Contract ending?") }) },
	RehireOutro = { PlaceObj('ChatMessage', { 'Text', T(890000000006215, --[[ModItemUnitDataCompositeDef Jazz_Meat Text RehireOutro ChatMessage voice:Jazz_Meat]] "Staying.") }) },
	MedicalDeposit = "small",
	StartingSalary = 750,
	SalaryIncrease = 150,
	SalaryLv1 = 300,
	SalaryMaxLv = 2200,
	StartingLevel = 3,
	CustomEquipGear = function (self, items)
	self:TryEquip(items, "Handheld A", "Firearm")
	self:TryEquip(items, "Handheld B", "Firearm")
	end,
	MaxHitPoints = 90,
	StartingPerks = {
	"Jazz_Perk_Meat",
	"MeleeTraining",
	"TrueGrit",
	},
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "Meat" }) },
	Equipment = { "Loot_JAZZ_Meat" },
	Tier = "Regular",
	Specialization = "ExplosiveExpert",
	pollyvoice = "Matthew",
	gender = "Male",
	VoiceResponseId = "Jazz_Meat",
	FallbackMissingVR = "Ice",
	DaysUntilOnline = 0,
}
