UndefineClass('Jazz_Grace')
DefineClass.Jazz_Grace = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AIM",
	Health = 81,
	Agility = 76,
	Dexterity = 85,
	Strength = 67,
	Wisdom = 82,
	Will = 45,
	Leadership = 42,
	Marksmanship = 72,
	Mechanical = 26,
	Explosives = 16,
	Medical = 26,
	Portrait = "Mod/Dv3mFVN/MercPortraits/Grace.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/Grace_Big.png",
	IsMercenary = true,
	Name = T(890000000004747, "Грациелла Джирелли"),
	Nick = T(890000000004748, "Грейс"),
	AllCapsNick = T(890000000004749, "ГРЕЙС"),
	Bio = T(890000000004750, "Грациелла Джирелли потомок итальянских иммигрантов в США. С одной стороны, она и в Италии-то не была ни разу, с другой стороны, порода видна невооруженным глазом. Как бы она не стралась сойти в Америке за свою, у нее не получалось. Что вынудило ее податься в наемники - не ясно, но из боевых навыков у нее, как минимум, неплохо поставлен бросок. Американский бейсбол."),
	Nationality = "Italy",
	Title = T(890000000004751, "Итальянка"),
	Email = T(890000000004752, "Grace@aim.com"),
	snype_nick = T(890000000004753, "graceful"),
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000004754, --[[ModItemUnitDataCompositeDef Jazz_Grace Text Offline ChatMessage voice:Jazz_Grace]] "Вы позвонили Грейс Джирелли, оставьте свое сообщение. Мама, если это ты... Да, я в порядке, и... нет, у меня нет времени для встречи с очередным милым молодым человеком. Я тебя люблю. Чао!") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000004755, --[[ModItemUnitDataCompositeDef Jazz_Grace Text GreetingAndOffer ChatMessage voice:Jazz_Grace]] "Говорит Грейс Джирелли.") }) },
	ConversationRestart = { PlaceObj('ChatMessage', { 'Text', T(890000000004756, --[[ModItemUnitDataCompositeDef Jazz_Grace Text ConversationRestart ChatMessage voice:Jazz_Grace]] "Я сказала...") }) },
	IdleLine = { PlaceObj('ChatMessage', { 'Text', T(890000000004757, --[[ModItemUnitDataCompositeDef Jazz_Grace Text IdleLine ChatMessage voice:Jazz_Grace]] "Кстати, я здорово управляюсь с ножами...") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000004758, --[[ModItemUnitDataCompositeDef Jazz_Grace Text PartingWords ChatMessage voice:Jazz_Grace]] "Прекрасно. Берегитесь, плохиши, кто не спрятался, я не виновата!") }) },
	RehireIntro = { PlaceObj('ChatMessage', { 'Text', T(890000000004759, --[[ModItemUnitDataCompositeDef Jazz_Grace Text RehireIntro ChatMessage voice:Jazz_Grace]] "Срок моего контракта истек, но я могу остаться, пупсик, если без меня вы не справитесь.") }) },
	RehireOutro = { PlaceObj('ChatMessage', { 'Text', T(890000000004760, --[[ModItemUnitDataCompositeDef Jazz_Grace Text RehireOutro ChatMessage voice:Jazz_Grace]] "Понято и принято.") }) },
	MedicalDeposit = "small",
	StartingSalary = 1600,
	SalaryIncrease = 150,
	SalaryLv1 = 600,
	SalaryMaxLv = 4000,
	StartingLevel = 2,
	CustomEquipGear = function (self, items)
	self:TryEquip(items, "Handheld A", "Firearm")
	self:TryEquip(items, "Handheld B", "Firearm")
	end,
	MaxHitPoints = 70,
	StartingPerks = {
	"Jazz_Perk_Grace",
	"Throwing",
	"Pessimist",
	"FirstThrow",
	},
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "Grace" }) },
	Equipment = { "Loot_JAZZ_Grace" },
	Tier = "Regular",
	Specialization = "AllRounder",
	pollyvoice = "Amy",
	gender = "Female",
	VoiceResponseId = "Jazz_Grace",
	FallbackMissingVR = "Ice",
	DaysUntilOnline = 0,
}
