UndefineClass('Jazz_Kulba')
DefineClass.Jazz_Kulba = {
	Dislikes = {
					"Ivan",
					"Igor",
					"Jazz_Ricochet",
				},
	DurationDiscount = "long only",
	Likes = {
					"Gus",
				},
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AIM",
	Health = 67,
	Agility = 51,
	Dexterity = 60,
	Strength = 66,
	Wisdom = 65,
	Will = 91,
	Leadership = 8,
	Marksmanship = 95,
	Mechanical = 88,
	Explosives = 2,
	Medical = 8,
	Portrait = "Mod/Dv3mFVN/MercPortraits/Kulba.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/Kulba_Big.png",
	IsMercenary = true,
	Name = T(890000000004715, "Джон Кульба"),
	Nick = T(890000000004716, "Кульба"),
	AllCapsNick = T(890000000004717, "КУЛЬБА"),
	Bio = T(890000000004718, "Джон Кульба - человек, везение которого принимает ровно два значения. Либо пан, либо пропал. Улетел по ошибке в страну, охваченную гражданской войной. Без потерь с вооруженным эскортом эвакуировался. Жена заболела неизлечимой формой рака кожи. Быстро и без мучений погибла при ограблении (хотя тут спорное везение, конечно). Джон в горе и печали отправился на перекладных в страну третьего мира. Снова повстречал там старых знакомых наемников, которым и решил составить компанию. Ему нечего терять, так что драться Джон будет до самого конца. Своего или врага - это как получится."),
	Nationality = "USA",
	Title = T(890000000004719, "Grandpa Independence"),
	Email = T(890000000004720, "Kulba@ub.mil"),
	snype_nick = T(890000000004721, "John"),
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000004722, --[[ModItemUnitDataCompositeDef Jazz_Kulba Text Offline ChatMessage voice:Jazz_Kulba]] "Кульба на службе. Перезвоните.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000004723, --[[ModItemUnitDataCompositeDef Jazz_Kulba Text GreetingAndOffer ChatMessage voice:Jazz_Kulba]] "Кульба слушает. За свободу.") }) },
	ConversationRestart = { PlaceObj('ChatMessage', { 'Text', T(890000000004724, --[[ModItemUnitDataCompositeDef Jazz_Kulba Text ConversationRestart ChatMessage voice:Jazz_Kulba]] "Связь прервалась. Вернёмся к делу.") }) },
	IdleLine = { PlaceObj('ChatMessage', { 'Text', T(890000000004725, --[[ModItemUnitDataCompositeDef Jazz_Kulba Text IdleLine ChatMessage voice:Jazz_Kulba]] "Старое оружие ещё послужит.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000004726, --[[ModItemUnitDataCompositeDef Jazz_Kulba Text PartingWords ChatMessage voice:Jazz_Kulba]] "За свободу. Я в деле.") }) },
	RehireIntro = { PlaceObj('ChatMessage', { 'Text', T(890000000004727, --[[ModItemUnitDataCompositeDef Jazz_Kulba Text RehireIntro ChatMessage voice:Jazz_Kulba]] "Контракт заканчивается. Продлеваем?") }) },
	RehireOutro = { PlaceObj('ChatMessage', { 'Text', T(890000000004728, --[[ModItemUnitDataCompositeDef Jazz_Kulba Text RehireOutro ChatMessage voice:Jazz_Kulba]] "Остаюсь. Есть ещё порох в пороховницах.") }) },
	MedicalDeposit = "large",
	StartingSalary = 510,
	SalaryIncrease = 220,
	SalaryLv1 = 350,
	SalaryMaxLv = 2200,
	StartingLevel = 2,
	CustomEquipGear = function (self, items)
	self:TryEquip(items, "Handheld A", "Firearm")
	self:TryEquip(items, "Handheld B", "Firearm")
	end,
	MaxHitPoints = 58,
	StartingPerks = {
	"Jazz_Perk_Kulba",
	"AutoWeapons",
	"MrFixit",
	"OldDog",
	},
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "Kulba" }) },
	Equipment = { "Loot_JAZZ_Kulba" },
	Tier = "Regular",
	Specialization = "Autoriflemen",
	pollyvoice = "Matthew",
	gender = "Male",
	VoiceResponseId = "Jazz_Kulba",
	FallbackMissingVR = "Ice",
	DaysUntilOnline = 0,
}
