UndefineClass('JAZZ_AME_24')
DefineClass.JAZZ_AME_24 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 80,
	Agility = 66,
	Dexterity = 66,
	Strength = 62,
	Wisdom = 54,
	Will = 26,
	Leadership = 5,
	Marksmanship = 56,
	Mechanical = 0,
	Explosives = 12,
	Medical = 5,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_24.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_24_Big.png",
	IsMercenary = true,
	Name = T(890000000005330, "Michel Kabeya") --[[ModItemUnitDataCompositeDef JAZZ_AME_24 Name]],
	Nick = T(890000000005331, "Michel") --[[ModItemUnitDataCompositeDef JAZZ_AME_24 Nick]],
	AllCapsNick = T(890000000005332, "MICHEL") --[[ModItemUnitDataCompositeDef JAZZ_AME_24 AllCapsNick]],
	Bio = T(890000000005333, "Мишель Кабейа из Конго всегда любил банки больше стволов. Настоящая работа для него начинается, когда свистит чека. Шумный в баре и тихий перед броском — и не притворяется героем.") --[[ModItemUnitDataCompositeDef JAZZ_AME_24 Bio]],
	Nationality = "Congo",
	HireStatus = "NotMet",
	AMECategory = "Fighters",
	AMERole = "Grenadier",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005334, "Дозвонился. Слушаю.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005335, "Ищу работу. Что предлагаете?") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005336, "До связи.") }) },
	MedicalDeposit = "none",
	StartingSalary = 250,
	StartingLevel = 1,
	StartingPerks = {
	"Throwing",
	},
	Specialization = "ExplosiveExpert",
	MaxHitPoints = 80,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_24" }) },
	Equipment = { "Loot_JAZZ_AME_24" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Low",
	FallbackMissingVR = "LegionRaider",
	DaysUntilOnline = 0,
}
