UndefineClass('JAZZ_AME_46')
DefineClass.JAZZ_AME_46 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 92,
	Agility = 60,
	Dexterity = 58,
	Strength = 92,
	Wisdom = 34,
	Will = 60,
	Leadership = 5,
	Marksmanship = 56,
	Mechanical = 0,
	Explosives = 8,
	Medical = 5,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_46.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_46_Big.png",
	IsMercenary = true,
	Name = T(890000000005550, "Kofi Mensah") --[[ModItemUnitDataCompositeDef JAZZ_AME_46 Name]],
	Nick = T(890000000005551, "Kofi") --[[ModItemUnitDataCompositeDef JAZZ_AME_46 Nick]],
	AllCapsNick = T(890000000005552, "KOFI") --[[ModItemUnitDataCompositeDef JAZZ_AME_46 AllCapsNick]],
	Bio = T(890000000005553, "Coarse rope rides at Kofi Mensah's waist for repairing crate handles everyone else has abandoned. He went from a Ghanaian dock winch to guns that made ordinary men seek another pair of hands. Immensely built, Kofi changes direction slowly and never chases what can be pinned down. Subtle plans can outrun his understanding, but weight and recoil seem to arrive at his shoulders already tamed.") --[[ModItemUnitDataCompositeDef JAZZ_AME_46 Bio]],
	Nationality = "Ghana",
	HireStatus = "NotMet",
	AMECategory = "Hardened",
	AMERole = "Machinegunner",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005554, "I'm here. Talk.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005555, "If there's work, I'm listening.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005556, "Send the terms.") }) },
	MedicalDeposit = "none",
	StartingSalary = 131,
	StartingLevel = 1,
	StartingPerks = {
	"HeavyWeaponsTraining",
	},
	Specialization = "HeavyWeapons",
	MaxHitPoints = 92,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_46" }) },
	Equipment = { "Loot_JAZZ_AME_46" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Hard",
	FallbackMissingVR = "ArmySoldier",
	DaysUntilOnline = 0,
}
