UndefineClass('JAZZ_AME_39')
DefineClass.JAZZ_AME_39 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 84,
	Agility = 70,
	Dexterity = 68,
	Strength = 72,
	Wisdom = 44,
	Will = 55,
	Leadership = 12,
	Marksmanship = 54,
	Mechanical = 0,
	Explosives = 10,
	Medical = 8,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_39.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_39_Big.png",
	IsMercenary = true,
	Name = T(890000000005480, "Joseph \"Hyena\" Mukendi") --[[ModItemUnitDataCompositeDef JAZZ_AME_39 Name]],
	Nick = T(890000000005481, "Hyena") --[[ModItemUnitDataCompositeDef JAZZ_AME_39 Nick]],
	AllCapsNick = T(890000000005482, "HYENA") --[[ModItemUnitDataCompositeDef JAZZ_AME_39 AllCapsNick]],
	Bio = T(890000000005483, "A dented pocket mirror lets Joseph “Hyena” Mukendi inspect a doorway without offering it his head. Grand Chien survivors remembered his ambush laugh before they remembered the face. Joseph fights with quick, practical cruelty and considers elegance a luxury for safer rooms. Nerve carries him through ugly moments, though his appetite for nearness can place him where a wiser man would never go.") --[[ModItemUnitDataCompositeDef JAZZ_AME_39 Bio]],
	Nationality = "GrandChien",
	HireStatus = "NotMet",
	AMECategory = "Hardened",
	AMERole = "Autorifleman",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005484, "I'm here. Talk.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005485, "If there's work, I'm listening.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005486, "Send the terms.") }) },
	MedicalDeposit = "none",
	StartingSalary = 127,
	StartingLevel = 1,
		StartingPerks = {
	"AutoWeapons",
	"CQCTraining",
	"Psycho",
	},,
	Specialization = "Autoriflemen",
	MaxHitPoints = 84,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_39" }) },
	Equipment = { "Loot_JAZZ_AME_39" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Hard",
	FallbackMissingVR = "ArmySoldier",
	DaysUntilOnline = 0,
}
