UndefineClass('Jazz_Vince')
DefineClass.Jazz_Vince = {
	DurationDiscount = "none",
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AIM",
	Health = 94,
	Agility = 49,
	Dexterity = 92,
	Strength = 69,
	Wisdom = 94,
	Will = 70,
	Leadership = 33,
	Marksmanship = 35,
	Mechanical = 13,
	Explosives = 3,
	Medical = 89,
	Portrait = "Mod/Dv3mFVN/MercPortraits/Vince.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/Vince_Big.png",
	IsMercenary = true,
	Name = T(890000000004667, "Доктор Винсент Воймонт"),
	Nick = T(890000000004668, "Винс"),
	AllCapsNick = T(890000000004669, "ВИНС"),
	Bio = T(890000000004670, "Врач из госпиталя Камбрии, в один момент решивший лично приложить руку к делу Революции в Арулько, так сказать. Собственно говоря, условия для него вряд ли улучшились - вместо хоть и бедной, но хотя бы по минимуму оборудованной больнички у него теперь вместо операционной - чистое поле, а вместо стола - расстеленная шинель. Но ему пока нравится."),
	Nationality = "USA",
	Title = T(890000000004671, "A Doctor Handy with Both Hands"),
	Email = T(890000000004672, "Vince@arulco.med"),
	snype_nick = T(890000000004673, "vince"),
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000004674, --[[ModItemUnitDataCompositeDef Jazz_Vince Text Offline ChatMessage voice:Jazz_Vince]] "Доктор Винс на операции. Перезвоните.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000004675, --[[ModItemUnitDataCompositeDef Jazz_Vince Text GreetingAndOffer ChatMessage voice:Jazz_Vince]] "Винсент слушает. Кого нужно подлатать?") }) },
	ConversationRestart = { PlaceObj('ChatMessage', { 'Text', T(890000000004676, --[[ModItemUnitDataCompositeDef Jazz_Vince Text ConversationRestart ChatMessage voice:Jazz_Vince]] "Связь прервалась. Вернёмся к делу.") }) },
	IdleLine = { PlaceObj('ChatMessage', { 'Text', T(890000000004677, --[[ModItemUnitDataCompositeDef Jazz_Vince Text IdleLine ChatMessage voice:Jazz_Vince]] "Всегда рад научить чему-то новому.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000004678, --[[ModItemUnitDataCompositeDef Jazz_Vince Text PartingWords ChatMessage voice:Jazz_Vince]] "Готов учить и лечить. Иду.") }) },
	RehireIntro = { PlaceObj('ChatMessage', { 'Text', T(890000000004679, --[[ModItemUnitDataCompositeDef Jazz_Vince Text RehireIntro ChatMessage voice:Jazz_Vince]] "Контракт заканчивается. Продлеваем?") }) },
	RehireOutro = { PlaceObj('ChatMessage', { 'Text', T(890000000004680, --[[ModItemUnitDataCompositeDef Jazz_Vince Text RehireOutro ChatMessage voice:Jazz_Vince]] "Остаюсь. Ещё многому могу научить.") }) },
	MedicalDeposit = "extreme",
	StartingSalary = 500,
	SalaryIncrease = 150,
	SalaryLv1 = 500,
	SalaryMaxLv = 4000,
	StartingLevel = 2,
	CustomEquipGear = function (self, items)
	self:TryEquip(items, "Handheld A", "Firearm")
	self:TryEquip(items, "Handheld B", "Firearm")
	end,
	MaxHitPoints = 94,
	StartingPerks = {
	"Jazz_Perk_Vince",
	"Claustrophobic",
	"Ambidextrous",
	"Teacher",
	},
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "Vince" }) },
	Equipment = { "Loot_JAZZ_Vince" },
	Tier = "Veteran",
	Specialization = "Doctor",
	pollyvoice = "Matthew",
	gender = "Male",
	VoiceResponseId = "Jazz_Vince",
	FallbackMissingVR = "Ice",
	DaysUntilOnline = 0,
}
