UndefineClass('JAZZ_AME_56')
DefineClass.JAZZ_AME_56 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 52,
	Agility = 66,
	Dexterity = 60,
	Strength = 46,
	Wisdom = 55,
	Will = 30,
	Leadership = 12,
	Marksmanship = 70,
	Mechanical = 15,
	Explosives = 0,
	Medical = 8,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_56.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_56_Big.png",
	IsMercenary = true,
	Name = T(890000000005650, "Lindiwe Mokoena") --[[ModItemUnitDataCompositeDef JAZZ_AME_56 Name]],
	Nick = T(890000000005651, "Lindiwe") --[[ModItemUnitDataCompositeDef JAZZ_AME_56 Nick]],
	AllCapsNick = T(890000000005652, "LINDIWE") --[[ModItemUnitDataCompositeDef JAZZ_AME_56 AllCapsNick]],
	Bio = T(890000000005653, "A tiny jar of matte black paint covers every fresh glint on Lindiwe Mokoena's metal before dusk. South African night observation taught her how a bright scratch betrays more than a careless footstep. Lindiwe is reserved and careful not to confuse courage with carrying too much. Daylight bustle drains her quickly, but darkness narrows the world into patient shapes she can read with unusual confidence.") --[[ModItemUnitDataCompositeDef JAZZ_AME_56 Bio]],
	Nationality = "SouthAfrica",
	HireStatus = "NotMet",
	AMECategory = "Specialists",
	AMERole = "Sniper",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005654, "I'm available. We can discuss a contract.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005655, "Go ahead. Tell me what the job needs.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005656, "Understood. I will wait for your terms.") }) },
	MedicalDeposit = "none",
	StartingSalary = 243,
	StartingLevel = 1,
		StartingPerks = {
	"NightOps",
	"Stealthy",
	},,
	Specialization = "Marksmen",
	MaxHitPoints = 52,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_56" }) },
	Equipment = { "Loot_JAZZ_AME_56" },
	gender = "Female",
	VoiceResponseId = "IMP_female_01",
	FallbackMissingVR = "IMP_female_01",
	DaysUntilOnline = 0,
}
