UndefineClass('JAZZ_AME_54')
DefineClass.JAZZ_AME_54 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 72,
	Agility = 46,
	Dexterity = 48,
	Strength = 58,
	Wisdom = 88,
	Will = 34,
	Leadership = 70,
	Marksmanship = 32,
	Mechanical = 55,
	Explosives = 30,
	Medical = 40,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_54.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_54_Big.png",
	IsMercenary = true,
	Name = T(890000000005630, "Maj. Théodore Ngalula") --[[ModItemUnitDataCompositeDef JAZZ_AME_54 Name]],
	Nick = T(890000000005631, "Maj.") --[[ModItemUnitDataCompositeDef JAZZ_AME_54 Nick]],
	AllCapsNick = T(890000000005632, "MAJ.") --[[ModItemUnitDataCompositeDef JAZZ_AME_54 AllCapsNick]],
	Bio = T(890000000005633, "Wire holds one arm of Major Théodore Ngalula's folding spectacles, a temporary fix kept for years. His Grand Chien career was spent teaching groups to survive after exhaustion stripped away ceremony. Théodore repeats an explanation until it works in ordinary language, often repairing a loose buckle while he talks. He moves like an older man now, but flawed plans still reveal themselves to him with uncomfortable speed.") --[[ModItemUnitDataCompositeDef JAZZ_AME_54 Bio]],
	Nationality = "GrandChien",
	HireStatus = "NotMet",
	AMECategory = "Specialists",
	AMERole = "Instructor",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005634, "I'm available. We can discuss a contract.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005635, "Go ahead. Tell me what the job needs.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005636, "Understood. I will wait for your terms.") }) },
	MedicalDeposit = "none",
	StartingSalary = 286,
	StartingLevel = 1,
	StartingPerks = {
	"Teacher",
	},
	Specialization = "Leader",
	MaxHitPoints = 72,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_54" }) },
	Equipment = { "Loot_JAZZ_AME_54" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Hard",
	FallbackMissingVR = "ArmySoldier",
	DaysUntilOnline = 0,
}
