UndefineClass('JAZZ_Legion_LeaderT3_Captain')
DefineClass.JAZZ_Legion_LeaderT3_Captain = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",


	comment = "Т3 Советник Captain | Командир-Стрелок",
	object_class = "UnitData",
	Health = 95,
	Agility = 90,
	Dexterity = 90,
	Strength = 80,
	Wisdom = 80,
	Will = 100,
	Leadership = 100,
	Marksmanship = 90,
	Mechanical = 100,
	Explosives = 70,
	Medical = 70,
	Portrait = "Mod/Dv3mFVN/EnemyPortraits/Legion/Captain.png",
	BigPortrait = "UI/Enemies/LegionRaider",
	Name = T(890000000000838, --[[ModItemUnitDataCompositeDef JAZZ_Legion_LeaderT3_Captain Name]] "Советник"),
	Randomization = true,
	elite = true,
	eliteCategory = "Legion",
	Affiliation = "Legion",
	StartingLevel = 6,
	villain = true,
	neutral_retaliate = true,
	AIKeywords = {
		"Control",
		"Sniper",
		"Marksman",
		"Smoke",
		"Explosives",
		"Leader",
	},
	archetype = "Legion_Frontliner",
	role = "Marksman",
	RepositionArchetype = "Legion_Frontliner",
	AlwaysUseOpeningAttack = true,
	OpeningAttackType = "Overwatch",
	MaxAttacks = 10,
	PickCustomArchetype = function (self, proto_context)
		return JazzAI_PickCombatStance(self, proto_context)
	end,
	CustomEquipGear = function (self, items)  end,
	MaxHitPoints = 50,
	StartingPerks = {
		"CQCTraining",
		"Spiritual",
		"BattleFocus",
		"RelentlessAdvance",
		"ShoulderToShoulder",
		"AutoWeapons",
		"Spotter",
		"TakeAim",
		"Shatterhand",
		"OnMyTarget",
		"Ironclad",
		"LightStep",
		"TrickShot",
		"LeadFromTheFront",
		"Hobbler",
		"LightningReactionNPC",
		"Instagib",
	},
	AppearancesList = {
		PlaceObj('AppearanceWeight', {
			'Preset', "LegionSergant_Stronger",
		}),
		PlaceObj('AppearanceWeight', {
			'Preset', "LegionSergant_Stronger_alt",
		}),
		PlaceObj('AppearanceWeight', {
			'Preset', "LegionSergant_Stronger_alt_2",
		}),
	},
	Equipment = {
		"Captain_Inventory",
	},
	AdditionalGroups = {
		PlaceObj('AdditionalGroup', {
			'Weight', 50,
			'Exclusive', true,
			'Name', "LegionMale_1",
		}),
		PlaceObj('AdditionalGroup', {
			'Weight', 50,
			'Exclusive', true,
			'Name', "LegionMale_2",
		}),
	},
	pollyvoice = "Joey",
	gender = "Male",
	VoiceResponseId = "LegionRaider",
}

