UndefineClass('JAZZ_AME_53')
DefineClass.JAZZ_AME_53 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 66,
	Agility = 50,
	Dexterity = 52,
	Strength = 50,
	Wisdom = 82,
	Will = 28,
	Leadership = 65,
	Marksmanship = 38,
	Mechanical = 42,
	Explosives = 22,
	Medical = 30,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_53.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_53_Big.png",
	IsMercenary = true,
	Name = T(890000000005620, "Sgt. Nadia Okonkwo") --[[ModItemUnitDataCompositeDef JAZZ_AME_53 Name]],
	Nick = T(890000000005621, "Nadia") --[[ModItemUnitDataCompositeDef JAZZ_AME_53 Nick]],
	AllCapsNick = T(890000000005622, "NADIA") --[[ModItemUnitDataCompositeDef JAZZ_AME_53 AllCapsNick]],
	Bio = T(890000000005623, "Сержант Надия Оконкво из Нигерии учит прицелу так, будто это одна профессия со стрельбой: научить попадать важнее, чем самой красиво попасть на глазах у начальства. В бой идёт редко, говорит часто — и обычно по делу. Её слушают даже те, кто не любит женщин с голосом громче их собственного.") --[[ModItemUnitDataCompositeDef JAZZ_AME_53 Bio]],
	Nationality = "Nigeria",
	HireStatus = "NotMet",
	AMECategory = "Specialists",
	AMERole = "Instructor",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005624, "На связи. Готов обсуждать контракт.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005625, "Слушаю. Расскажите о задаче.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005626, "До связи.") }) },
	MedicalDeposit = "none",
	StartingSalary = 243,
	StartingLevel = 1,
	StartingPerks = {
	"Teacher",
	},
	Specialization = "Leader",
	MaxHitPoints = 66,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_53" }) },
	Equipment = { "Loot_JAZZ_AME_53" },
	gender = "Female",
	VoiceResponseId = "IMP_female_01",
	FallbackMissingVR = "IMP_female_01",
	DaysUntilOnline = 0,
}
