UndefineClass('JAZZ_AME_38')
DefineClass.JAZZ_AME_38 = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",

	object_class = "UnitData",
	Affiliation = "AME",
	Health = 82,
	Agility = 64,
	Dexterity = 64,
	Strength = 64,
	Wisdom = 54,
	Will = 32,
	Leadership = 50,
	Marksmanship = 56,
	Mechanical = 0,
	Explosives = 0,
	Medical = 5,
	Portrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_38.png",
	BigPortrait = "Mod/Dv3mFVN/MercPortraits/JAZZ_AME_38_Big.png",
	IsMercenary = true,
	Name = T(890000000005470, "Noah van Wyk") --[[ModItemUnitDataCompositeDef JAZZ_AME_38 Name]],
	Nick = T(890000000005471, "Noah") --[[ModItemUnitDataCompositeDef JAZZ_AME_38 Nick]],
	AllCapsNick = T(890000000005472, "NOAH") --[[ModItemUnitDataCompositeDef JAZZ_AME_38 AllCapsNick]],
	Bio = T(890000000005473, "A pocket ledger mixes Noah van Wyk's planting dates with promises made to people, every fulfilled one neatly crossed through. South African neighbours once brought him quarrels about water, fences, and wandering cattle. Noah speaks without hurry, leaving silence to push where louder men would shout. He is capable rather than dazzling with a rifle, but tired companions often recover their sense when his plain voice gives the next step.") --[[ModItemUnitDataCompositeDef JAZZ_AME_38 Bio]],
	Nationality = "SouthAfrica",
	HireStatus = "NotMet",
	AMECategory = "Fighters",
	AMERole = "Rifle",
	Offline = { PlaceObj('ChatMessage', { 'Text', T(890000000005474, "On the line.") }) },
	GreetingAndOffer = { PlaceObj('ChatMessage', { 'Text', T(890000000005475, "I'm listening. Tell me about the job.") }) },
	PartingWords = { PlaceObj('ChatMessage', { 'Text', T(890000000005476, "Understood. I'll be here.") }) },
	MedicalDeposit = "none",
	StartingSalary = 72,
	StartingLevel = 1,
	StartingPerks = {
	"Optimist",
	},
	Specialization = "Marksmen",
	MaxHitPoints = 82,
	AppearancesList = { PlaceObj('AppearanceWeight', { 'Preset', "JAZZ_AME_38" }) },
	Equipment = { "Loot_JAZZ_AME_38" },
	gender = "Male",
	VoiceResponseId = "Jazz_AME_Male_Hard",
	FallbackMissingVR = "ArmySoldier",
	DaysUntilOnline = 0,
}
