UndefineClass('ThugBoss')
DefineClass.ThugBoss = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",


	object_class = "UnitData",
	Health = 90,
	Agility = 85,
	Dexterity = 85,
	Strength = 80,
	Wisdom = 70,
	Will = 90,
	Leadership = 80,
	Marksmanship = 88,
	Mechanical = 100,
	Explosives = 50,
	Medical = 50,
	Portrait = "UI/EnemiesPortraits/ThugOfficer",
	Name = T(641400217995, --[[ModItemUnitDataCompositeDef ThugBoss Name]] "Командир"),
	Randomization = true,
	elite = true,
	Affiliation = "Thugs",
	StartingLevel = 7,
	villain = true,
	neutral_retaliate = true,
	AIKeywords = {
		"Control",
		"Smoke",
		"Explosives",
		"Soldier",
		"Ordnance",
		"Leader",
	},
	archetype = "Legion_Frontliner",
	role = "Commander",
	RepositionArchetype = "Legion_Frontliner",
	AlwaysUseOpeningAttack = true,
	OpeningAttackType = "Overwatch",
	MaxAttacks = 10,
	PickCustomArchetype = function (self, proto_context)  end,
	CustomEquipGear = function (self, items)  end,
	MaxHitPoints = 80,
	StartingPerks = {
		"CQCTraining",
		"Spiritual",
		"BattleFocus",
		"RelentlessAdvance",
		"ShoulderToShoulder",
		"AutoWeapons",
		"Spotter",
		"SidneyPerk",
		"TakeAim",
		"OnMyTarget",
		"Ironclad",
		"LightStep",
		"TrickShot",
		"LeadFromTheFront",
		"Hobbler",
		"Shatterhand",
		"LightningReactionNPC",
		"StressManagement",
		"Hotblood",
		"Instagib",
		"HitTheDeck",
		"CollateralDamage",
	},
	AppearancesList = {
		PlaceObj('AppearanceWeight', {
			'Preset', "Thug_Officer",
		}),
		PlaceObj('AppearanceWeight', {
			'Preset', "Thug_Officer_1",
		}),
	},
	Equipment = {
		"Lieutenant_Inventory",
	},
	AdditionalGroups = {
		PlaceObj('AdditionalGroup', {
			'Weight', 50,
			'Exclusive', true,
			'Name', "LegionMale_1",
		}),
		PlaceObj('AdditionalGroup', {
			'Weight', 50,
			'Exclusive', true,
			'Name', "LegionMale_2",
		}),
	},
	pollyvoice = "Joey",
	gender = "Male",
	VoiceResponseId = "LegionRaider",
}

