UndefineClass('ThugBoss_Stronger_Elite')
DefineClass.ThugBoss_Stronger_Elite = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",


	object_class = "UnitData",
	Health = 95,
	Agility = 90,
	Dexterity = 90,
	Strength = 80,
	Wisdom = 80,
	Will = 100,
	Leadership = 100,
	Marksmanship = 90,
	Mechanical = 100,
	Explosives = 70,
	Medical = 70,
	Portrait = "UI/EnemiesPortraits/ThugOfficer",
	Name = T(927223711798, --[[ModItemUnitDataCompositeDef ThugBoss_Stronger_Elite Name]] "Советник"),
	Randomization = true,
	elite = true,
	Affiliation = "Thugs",
	StartingLevel = 6,
	villain = true,
	neutral_retaliate = true,
	AIKeywords = {
		"Control",
		"Sniper",
		"Marksman",
		"Smoke",
		"Explosives",
		"Leader",
	},
	archetype = "Legion_Frontliner",
	role = "Marksman",
	RepositionArchetype = "Legion_Frontliner",
	AlwaysUseOpeningAttack = true,
	OpeningAttackType = "Overwatch",
	MaxAttacks = 10,
	PickCustomArchetype = function (self, proto_context)  end,
	CustomEquipGear = function (self, items)  end,
	MaxHitPoints = 50,
	StartingPerks = {
		"CQCTraining",
		"Spiritual",
		"BattleFocus",
		"RelentlessAdvance",
		"ShoulderToShoulder",
		"AutoWeapons",
		"Spotter",
		"TakeAim",
		"Shatterhand",
		"OnMyTarget",
		"Ironclad",
		"LightStep",
		"TrickShot",
		"LeadFromTheFront",
		"Shatterhand",
		"Hobbler",
		"LightningReactionNPC",
		"Instagib",
	},
	AppearancesList = {
		PlaceObj('AppearanceWeight', {
			'Preset', "Thug_Officer",
		}),
		PlaceObj('AppearanceWeight', {
			'Preset', "Thug_Officer_1",
		}),
	},
	Equipment = {
		"Captain_Inventory",
	},
	AdditionalGroups = {
		PlaceObj('AdditionalGroup', {
			'Weight', 50,
			'Exclusive', true,
			'Name', "LegionMale_1",
		}),
		PlaceObj('AdditionalGroup', {
			'Weight', 50,
			'Exclusive', true,
			'Name', "LegionMale_2",
		}),
	},
	pollyvoice = "Joey",
	gender = "Male",
	VoiceResponseId = "LegionRaider",
}

